[info]
relay_url = "wss://relay.staging.hostr.network/"
name = "staging.hostr.network"
description = "Our relay hosts information about p2p accomodation"

[network]
address = "0.0.0.0"
port = 8080

[options]
reject_future_seconds = 1800

[limits]
messages_per_sec = 10

secret_key = "<nostr nsec>"
