// Mocks generated by Mockito 5.4.6 from annotations
// in hostr/mocks/main.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:flutter_bloc/flutter_bloc.dart' as _i12;
import 'package:hostr/core/main.dart' as _i2;
import 'package:hostr/data/sources/local/key_storage.dart' as _i7;
import 'package:hostr/data/sources/local/nwc_storage.dart' as _i10;
import 'package:hostr/data/sources/local/secure_storage.dart' as _i4;
import 'package:hostr/data/sources/nostr/nostr/usecase/nwc/nwc.cubit.dart'
    as _i6;
import 'package:hostr/data/sources/nostr/nostr/usecase/nwc/nwc.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:ndk/ndk.dart' as _i11;
import 'package:ndk/shared/nips/nip01/key_pair.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCustomLogger_0 extends _i1.SmartFake implements _i2.CustomLogger {
  _FakeCustomLogger_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKeyPair_1 extends _i1.SmartFake implements _i3.KeyPair {
  _FakeKeyPair_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSecureStorage_2 extends _i1.SmartFake implements _i4.SecureStorage {
  _FakeSecureStorage_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNwc_3 extends _i1.SmartFake implements _i5.Nwc {
  _FakeNwc_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNwcCubitState_4 extends _i1.SmartFake implements _i6.NwcCubitState {
  _FakeNwcCubitState_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [KeyStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockKeyStorage extends _i1.Mock implements _i7.KeyStorage {
  MockKeyStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_0(this, Invocation.getter(#logger)),
          )
          as _i2.CustomLogger);

  @override
  set logger(_i2.CustomLogger? value) => super.noSuchMethod(
    Invocation.setter(#logger, value),
    returnValueForMissingStub: null,
  );

  @override
  set keyPair(_i3.KeyPair? value) => super.noSuchMethod(
    Invocation.setter(#keyPair, value),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<_i3.KeyPair?> getActiveKeyPair() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveKeyPair, []),
            returnValue: _i8.Future<_i3.KeyPair?>.value(),
          )
          as _i8.Future<_i3.KeyPair?>);

  @override
  _i8.Future<String> set(String? item) =>
      (super.noSuchMethod(
            Invocation.method(#set, [item]),
            returnValue: _i8.Future<String>.value(
              _i9.dummyValue<String>(this, Invocation.method(#set, [item])),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<dynamic> get() =>
      (super.noSuchMethod(
            Invocation.method(#get, []),
            returnValue: _i8.Future<dynamic>.value(),
          )
          as _i8.Future<dynamic>);

  @override
  _i3.KeyPair create() =>
      (super.noSuchMethod(
            Invocation.method(#create, []),
            returnValue: _FakeKeyPair_1(this, Invocation.method(#create, [])),
          )
          as _i3.KeyPair);

  @override
  _i8.Future<dynamic> wipe() =>
      (super.noSuchMethod(
            Invocation.method(#wipe, []),
            returnValue: _i8.Future<dynamic>.value(),
          )
          as _i8.Future<dynamic>);
}

/// A class which mocks [NwcStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockNwcStorage extends _i1.Mock implements _i10.NwcStorage {
  MockNwcStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.SecureStorage get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeSecureStorage_2(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i4.SecureStorage);

  @override
  _i2.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_0(this, Invocation.getter(#logger)),
          )
          as _i2.CustomLogger);

  @override
  _i8.Future<List<dynamic>> get() =>
      (super.noSuchMethod(
            Invocation.method(#get, []),
            returnValue: _i8.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i8.Future<List<dynamic>>);

  @override
  _i8.Future<Uri?> getUri() =>
      (super.noSuchMethod(
            Invocation.method(#getUri, []),
            returnValue: _i8.Future<Uri?>.value(),
          )
          as _i8.Future<Uri?>);

  @override
  _i8.Future<void> set(List<String>? items) =>
      (super.noSuchMethod(
            Invocation.method(#set, [items]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> wipe() =>
      (super.noSuchMethod(
            Invocation.method(#wipe, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [NwcCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockNwcCubit extends _i1.Mock implements _i6.NwcCubit {
  MockNwcCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_0(this, Invocation.getter(#logger)),
          )
          as _i2.CustomLogger);

  @override
  _i5.Nwc get nwc =>
      (super.noSuchMethod(
            Invocation.getter(#nwc),
            returnValue: _FakeNwc_3(this, Invocation.getter(#nwc)),
          )
          as _i5.Nwc);

  @override
  set url(String? value) => super.noSuchMethod(
    Invocation.setter(#url, value),
    returnValueForMissingStub: null,
  );

  @override
  set connection(_i11.NwcConnection? value) => super.noSuchMethod(
    Invocation.setter(#connection, value),
    returnValueForMissingStub: null,
  );

  @override
  _i6.NwcCubitState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeNwcCubitState_4(this, Invocation.getter(#state)),
          )
          as _i6.NwcCubitState);

  @override
  _i8.Stream<_i6.NwcCubitState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i8.Stream<_i6.NwcCubitState>.empty(),
          )
          as _i8.Stream<_i6.NwcCubitState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i8.Future<dynamic> connect(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [url]),
            returnValue: _i8.Future<dynamic>.value(),
          )
          as _i8.Future<dynamic>);

  @override
  _i8.Future<dynamic> checkInfo() =>
      (super.noSuchMethod(
            Invocation.method(#checkInfo, []),
            returnValue: _i8.Future<dynamic>.value(),
          )
          as _i8.Future<dynamic>);

  @override
  void emit(_i6.NwcCubitState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i12.Change<_i6.NwcCubitState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}
