// Mocks generated by Mockito 5.4.6 from annotations
// in hostr_sdk/mocks/usecase_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i24;

import 'package:hostr_sdk/usecase/auth/auth.dart' as _i8;
import 'package:hostr_sdk/usecase/badge_awards/badge_awards.dart' as _i34;
import 'package:hostr_sdk/usecase/badge_definitions/badge_definitions.dart'
    as _i33;
import 'package:hostr_sdk/usecase/escrow/escrow.dart' as _i30;
import 'package:hostr_sdk/usecase/escrow/operations/fund/escrow_fund_models.dart'
    as _i31;
import 'package:hostr_sdk/usecase/escrow/operations/fund/escrow_fund_operation.dart'
    as _i15;
import 'package:hostr_sdk/usecase/escrow/supported_escrow_contract/supported_escrow_contract.dart'
    as _i32;
import 'package:hostr_sdk/usecase/escrow_methods/escrows_methods.dart' as _i16;
import 'package:hostr_sdk/usecase/escrow_trusts/escrow_trusts.dart' as _i13;
import 'package:hostr_sdk/usecase/escrows/escrows.dart' as _i12;
import 'package:hostr_sdk/usecase/evm/chain/evm_chain.dart' as _i22;
import 'package:hostr_sdk/usecase/evm/chain/rootstock/rootstock.dart' as _i21;
import 'package:hostr_sdk/usecase/evm/evm.dart' as _i14;
import 'package:hostr_sdk/usecase/listings/listings.dart' as _i28;
import 'package:hostr_sdk/usecase/messaging/messaging.dart' as _i11;
import 'package:hostr_sdk/usecase/messaging/threads.dart' as _i17;
import 'package:hostr_sdk/usecase/metadata/metadata.dart' as _i26;
import 'package:hostr_sdk/usecase/nwc/nwc.cubit.dart' as _i27;
import 'package:hostr_sdk/usecase/nwc/nwc.dart' as _i9;
import 'package:hostr_sdk/usecase/payments/operations/pay_models.dart' as _i19;
import 'package:hostr_sdk/usecase/payments/operations/pay_operation.dart'
    as _i20;
import 'package:hostr_sdk/usecase/payments/payments.dart' as _i36;
import 'package:hostr_sdk/usecase/relays/relays.dart' as _i37;
import 'package:hostr_sdk/usecase/requests/requests.dart' as _i7;
import 'package:hostr_sdk/usecase/reservation_requests/reservation_requests.dart'
    as _i35;
import 'package:hostr_sdk/usecase/reservations/reservations.dart' as _i29;
import 'package:hostr_sdk/usecase/storage/storage.dart' as _i3;
import 'package:hostr_sdk/usecase/zaps/zaps.dart' as _i18;
import 'package:hostr_sdk/util/main.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:models/main.dart' as _i10;
import 'package:ndk/entities.dart' as _i25;
import 'package:ndk/ndk.dart' as _i2;
import 'package:ndk/shared/nips/nip01/key_pair.dart' as _i23;
import 'package:rxdart/rxdart.dart' as _i4;
import 'package:web3dart/web3dart.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNdk_0 extends _i1.SmartFake implements _i2.Ndk {
  _FakeNdk_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthStorage_1 extends _i1.SmartFake implements _i3.AuthStorage {
  _FakeAuthStorage_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValueStream_2<T> extends _i1.SmartFake
    implements _i4.ValueStream<T> {
  _FakeValueStream_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEthPrivateKey_3 extends _i1.SmartFake implements _i5.EthPrivateKey {
  _FakeEthPrivateKey_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamWithStatus_4<T1> extends _i1.SmartFake
    implements _i6.StreamWithStatus<T1> {
  _FakeStreamWithStatus_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRequests_5 extends _i1.SmartFake implements _i7.Requests {
  _FakeRequests_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuth_6 extends _i1.SmartFake implements _i8.Auth {
  _FakeAuth_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCustomLogger_7 extends _i1.SmartFake implements _i6.CustomLogger {
  _FakeCustomLogger_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNwcStorage_8 extends _i1.SmartFake implements _i3.NwcStorage {
  _FakeNwcStorage_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNwcConnection_9 extends _i1.SmartFake implements _i2.NwcConnection {
  _FakeNwcConnection_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetInfoResponse_10 extends _i1.SmartFake
    implements _i2.GetInfoResponse {
  _FakeGetInfoResponse_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePayInvoiceResponse_11 extends _i1.SmartFake
    implements _i2.PayInvoiceResponse {
  _FakePayInvoiceResponse_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLookupInvoiceResponse_12 extends _i1.SmartFake
    implements _i2.LookupInvoiceResponse {
  _FakeLookupInvoiceResponse_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNwc_13 extends _i1.SmartFake implements _i9.Nwc {
  _FakeNwc_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeZapResponse_14 extends _i1.SmartFake implements _i2.ZapResponse {
  _FakeZapResponse_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeListing_15 extends _i1.SmartFake implements _i10.Listing {
  _FakeListing_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessaging_16 extends _i1.SmartFake implements _i11.Messaging {
  _FakeMessaging_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReservation_17 extends _i1.SmartFake implements _i10.Reservation {
  _FakeReservation_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEscrows_18 extends _i1.SmartFake implements _i12.Escrows {
  _FakeEscrows_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEscrowTrusts_19 extends _i1.SmartFake implements _i13.EscrowTrusts {
  _FakeEscrowTrusts_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEvm_20 extends _i1.SmartFake implements _i14.Evm {
  _FakeEvm_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEscrowFundOperation_21 extends _i1.SmartFake
    implements _i15.EscrowFundOperation {
  _FakeEscrowFundOperation_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEscrowMethods_22 extends _i1.SmartFake
    implements _i16.EscrowMethods {
  _FakeEscrowMethods_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMutualEscrowResult_23 extends _i1.SmartFake
    implements _i12.MutualEscrowResult {
  _FakeMutualEscrowResult_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEscrowService_24 extends _i1.SmartFake
    implements _i10.EscrowService {
  _FakeEscrowService_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEscrowTrust_25 extends _i1.SmartFake implements _i10.EscrowTrust {
  _FakeEscrowTrust_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEscrowMethod_26 extends _i1.SmartFake implements _i10.EscrowMethod {
  _FakeEscrowMethod_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBadgeDefinition_27 extends _i1.SmartFake
    implements _i10.BadgeDefinition {
  _FakeBadgeDefinition_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBadgeAward_28 extends _i1.SmartFake implements _i10.BadgeAward {
  _FakeBadgeAward_28(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeThreads_29 extends _i1.SmartFake implements _i17.Threads {
  _FakeThreads_29(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNip01Event_30 extends _i1.SmartFake implements _i2.Nip01Event {
  _FakeNip01Event_30(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessage_31<T extends _i10.Event> extends _i1.SmartFake
    implements _i10.Message<T> {
  _FakeMessage_31(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReservationRequest_32 extends _i1.SmartFake
    implements _i10.ReservationRequest {
  _FakeReservationRequest_32(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeZaps_33 extends _i1.SmartFake implements _i18.Zaps {
  _FakeZaps_33(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePayOperation_34<
  T extends _i19.PayParameters,
  RD extends _i19.ResolvedDetails,
  CD extends _i19.CallbackDetails,
  CmpD extends _i19.CompletedDetails
>
    extends _i1.SmartFake
    implements _i20.PayOperation<T, RD, CD, CmpD> {
  _FakePayOperation_34(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRootstock_35 extends _i1.SmartFake implements _i21.Rootstock {
  _FakeRootstock_35(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBitcoinAmount_36 extends _i1.SmartFake implements _i6.BitcoinAmount {
  _FakeBitcoinAmount_36(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEvmChain_37 extends _i1.SmartFake implements _i22.EvmChain {
  _FakeEvmChain_37(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRelayStorage_38 extends _i1.SmartFake implements _i3.RelayStorage {
  _FakeRelayStorage_38(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Auth].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuth extends _i1.Mock implements _i8.Auth {
  MockAuth() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Ndk get ndk =>
      (super.noSuchMethod(
            Invocation.getter(#ndk),
            returnValue: _FakeNdk_0(this, Invocation.getter(#ndk)),
          )
          as _i2.Ndk);

  @override
  _i3.AuthStorage get authStorage =>
      (super.noSuchMethod(
            Invocation.getter(#authStorage),
            returnValue: _FakeAuthStorage_1(
              this,
              Invocation.getter(#authStorage),
            ),
          )
          as _i3.AuthStorage);

  @override
  _i4.ValueStream<_i8.AuthState> get authState =>
      (super.noSuchMethod(
            Invocation.getter(#authState),
            returnValue: _FakeValueStream_2<_i8.AuthState>(
              this,
              Invocation.getter(#authState),
            ),
          )
          as _i4.ValueStream<_i8.AuthState>);

  @override
  set activeKeyPair(_i23.KeyPair? value) => super.noSuchMethod(
    Invocation.setter(#activeKeyPair, value),
    returnValueForMissingStub: null,
  );

  @override
  _i24.Future<void> signup() =>
      (super.noSuchMethod(
            Invocation.method(#signup, []),
            returnValue: _i24.Future<void>.value(),
            returnValueForMissingStub: _i24.Future<void>.value(),
          )
          as _i24.Future<void>);

  @override
  _i24.Future<void> signin(String? input) =>
      (super.noSuchMethod(
            Invocation.method(#signin, [input]),
            returnValue: _i24.Future<void>.value(),
            returnValueForMissingStub: _i24.Future<void>.value(),
          )
          as _i24.Future<void>);

  @override
  _i24.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i24.Future<void>.value(),
            returnValueForMissingStub: _i24.Future<void>.value(),
          )
          as _i24.Future<void>);

  @override
  _i24.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i24.Future<void>.value(),
            returnValueForMissingStub: _i24.Future<void>.value(),
          )
          as _i24.Future<void>);

  @override
  _i24.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i24.Future<bool>.value(false),
          )
          as _i24.Future<bool>);

  @override
  bool ensureNdkAccountsMatch() =>
      (super.noSuchMethod(
            Invocation.method(#ensureNdkAccountsMatch, []),
            returnValue: false,
          )
          as bool);

  @override
  _i5.EthPrivateKey getActiveEvmKey() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveEvmKey, []),
            returnValue: _FakeEthPrivateKey_3(
              this,
              Invocation.method(#getActiveEvmKey, []),
            ),
          )
          as _i5.EthPrivateKey);

  @override
  _i24.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i24.Future<void>.value(),
            returnValueForMissingStub: _i24.Future<void>.value(),
          )
          as _i24.Future<void>);
}

/// A class which mocks [Requests].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequests extends _i1.Mock implements _i7.Requests {
  MockRequests() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Ndk get ndk =>
      (super.noSuchMethod(
            Invocation.getter(#ndk),
            returnValue: _FakeNdk_0(this, Invocation.getter(#ndk)),
          )
          as _i2.Ndk);

  @override
  _i6.StreamWithStatus<T> subscribe<T extends _i2.Nip01Event>({
    required _i2.Filter? filter,
    List<String>? relays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [], {
              #filter: filter,
              #relays: relays,
            }),
            returnValue: _FakeStreamWithStatus_4<T>(
              this,
              Invocation.method(#subscribe, [], {
                #filter: filter,
                #relays: relays,
              }),
            ),
          )
          as _i6.StreamWithStatus<T>);

  @override
  _i24.Stream<T> query<T extends _i2.Nip01Event>({
    required _i2.Filter? filter,
    List<String>? relays,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#query, [], {
              #filter: filter,
              #relays: relays,
              #timeout: timeout,
            }),
            returnValue: _i24.Stream<T>.empty(),
          )
          as _i24.Stream<T>);

  @override
  _i24.Future<int> count({
    required _i2.Filter? filter,
    Duration? timeout,
    List<String>? relays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#count, [], {
              #filter: filter,
              #timeout: timeout,
              #relays: relays,
            }),
            returnValue: _i24.Future<int>.value(0),
          )
          as _i24.Future<int>);

  @override
  _i24.Future<List<_i25.RelayBroadcastResponse>> broadcast({
    required _i2.Nip01Event? event,
    List<String>? relays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#broadcast, [], {#event: event, #relays: relays}),
            returnValue: _i24.Future<List<_i25.RelayBroadcastResponse>>.value(
              <_i25.RelayBroadcastResponse>[],
            ),
          )
          as _i24.Future<List<_i25.RelayBroadcastResponse>>);

  @override
  _i24.Future<void> mock() =>
      (super.noSuchMethod(
            Invocation.method(#mock, []),
            returnValue: _i24.Future<void>.value(),
            returnValueForMissingStub: _i24.Future<void>.value(),
          )
          as _i24.Future<void>);
}

/// A class which mocks [MetadataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockMetadataUseCase extends _i1.Mock implements _i26.MetadataUseCase {
  MockMetadataUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Requests get requests =>
      (super.noSuchMethod(
            Invocation.getter(#requests),
            returnValue: _FakeRequests_5(this, Invocation.getter(#requests)),
          )
          as _i7.Requests);

  @override
  _i8.Auth get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeAuth_6(this, Invocation.getter(#auth)),
          )
          as _i8.Auth);

  @override
  set requests(_i7.Requests? value) => super.noSuchMethod(
    Invocation.setter(#requests, value),
    returnValueForMissingStub: null,
  );

  @override
  set auth(_i8.Auth? value) => super.noSuchMethod(
    Invocation.setter(#auth, value),
    returnValueForMissingStub: null,
  );

  @override
  _i24.Future<_i10.ProfileMetadata?> loadMetadata(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#loadMetadata, [pubkey]),
            returnValue: _i24.Future<_i10.ProfileMetadata?>.value(),
          )
          as _i24.Future<_i10.ProfileMetadata?>);

  @override
  _i24.Future<_i24.Future<List<_i25.RelayBroadcastResponse>>>
  upsertMetadata() =>
      (super.noSuchMethod(
            Invocation.method(#upsertMetadata, []),
            returnValue:
                _i24.Future<
                  _i24.Future<List<_i25.RelayBroadcastResponse>>
                >.value(
                  _i24.Future<List<_i25.RelayBroadcastResponse>>.value(
                    <_i25.RelayBroadcastResponse>[],
                  ),
                ),
          )
          as _i24.Future<_i24.Future<List<_i25.RelayBroadcastResponse>>>);
}

/// A class which mocks [Nwc].
///
/// See the documentation for Mockito's code generation for more information.
class MockNwc extends _i1.Mock implements _i9.Nwc {
  MockNwc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_7(this, Invocation.getter(#logger)),
          )
          as _i6.CustomLogger);

  @override
  _i3.NwcStorage get nwcStorage =>
      (super.noSuchMethod(
            Invocation.getter(#nwcStorage),
            returnValue: _FakeNwcStorage_8(
              this,
              Invocation.getter(#nwcStorage),
            ),
          )
          as _i3.NwcStorage);

  @override
  _i2.Ndk get ndk =>
      (super.noSuchMethod(
            Invocation.getter(#ndk),
            returnValue: _FakeNdk_0(this, Invocation.getter(#ndk)),
          )
          as _i2.Ndk);

  @override
  List<_i27.NwcCubit> get connections =>
      (super.noSuchMethod(
            Invocation.getter(#connections),
            returnValue: <_i27.NwcCubit>[],
          )
          as List<_i27.NwcCubit>);

  @override
  _i24.Stream<List<_i27.NwcCubit>> get connectionsStream =>
      (super.noSuchMethod(
            Invocation.getter(#connectionsStream),
            returnValue: _i24.Stream<List<_i27.NwcCubit>>.empty(),
          )
          as _i24.Stream<List<_i27.NwcCubit>>);

  @override
  set nwcStorage(_i3.NwcStorage? value) => super.noSuchMethod(
    Invocation.setter(#nwcStorage, value),
    returnValueForMissingStub: null,
  );

  @override
  set ndk(_i2.Ndk? value) => super.noSuchMethod(
    Invocation.setter(#ndk, value),
    returnValueForMissingStub: null,
  );

  @override
  set connections(List<_i27.NwcCubit>? value) => super.noSuchMethod(
    Invocation.setter(#connections, value),
    returnValueForMissingStub: null,
  );

  @override
  _i24.Future<void> save() =>
      (super.noSuchMethod(
            Invocation.method(#save, []),
            returnValue: _i24.Future<void>.value(),
            returnValueForMissingStub: _i24.Future<void>.value(),
          )
          as _i24.Future<void>);

  @override
  _i24.Future<void> add(_i27.NwcCubit? reactiveConnection) =>
      (super.noSuchMethod(
            Invocation.method(#add, [reactiveConnection]),
            returnValue: _i24.Future<void>.value(),
            returnValueForMissingStub: _i24.Future<void>.value(),
          )
          as _i24.Future<void>);

  @override
  _i24.Future<void> remove(_i27.NwcCubit? reactiveConnection) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [reactiveConnection]),
            returnValue: _i24.Future<void>.value(),
            returnValueForMissingStub: _i24.Future<void>.value(),
          )
          as _i24.Future<void>);

  @override
  _i24.Future<_i2.NwcConnection> connect(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [url]),
            returnValue: _i24.Future<_i2.NwcConnection>.value(
              _FakeNwcConnection_9(this, Invocation.method(#connect, [url])),
            ),
          )
          as _i24.Future<_i2.NwcConnection>);

  @override
  _i24.Future<_i2.GetInfoResponse> getInfo(_i2.NwcConnection? connection) =>
      (super.noSuchMethod(
            Invocation.method(#getInfo, [connection]),
            returnValue: _i24.Future<_i2.GetInfoResponse>.value(
              _FakeGetInfoResponse_10(
                this,
                Invocation.method(#getInfo, [connection]),
              ),
            ),
          )
          as _i24.Future<_i2.GetInfoResponse>);

  @override
  _i24.Future<_i2.PayInvoiceResponse> payInvoice(
    _i2.NwcConnection? connection,
    String? invoice,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#payInvoice, [connection, invoice]),
            returnValue: _i24.Future<_i2.PayInvoiceResponse>.value(
              _FakePayInvoiceResponse_11(
                this,
                Invocation.method(#payInvoice, [connection, invoice]),
              ),
            ),
          )
          as _i24.Future<_i2.PayInvoiceResponse>);

  @override
  _i24.Future<_i2.LookupInvoiceResponse> lookupInvoice(
    _i2.NwcConnection? connection, {
    String? paymentHash,
    String? invoice,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #lookupInvoice,
              [connection],
              {#paymentHash: paymentHash, #invoice: invoice},
            ),
            returnValue: _i24.Future<_i2.LookupInvoiceResponse>.value(
              _FakeLookupInvoiceResponse_12(
                this,
                Invocation.method(
                  #lookupInvoice,
                  [connection],
                  {#paymentHash: paymentHash, #invoice: invoice},
                ),
              ),
            ),
          )
          as _i24.Future<_i2.LookupInvoiceResponse>);

  @override
  _i24.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i24.Future<void>.value(),
            returnValueForMissingStub: _i24.Future<void>.value(),
          )
          as _i24.Future<void>);

  @override
  void start() => super.noSuchMethod(
    Invocation.method(#start, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [Zaps].
///
/// See the documentation for Mockito's code generation for more information.
class MockZaps extends _i1.Mock implements _i18.Zaps {
  MockZaps() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Nwc get nwc =>
      (super.noSuchMethod(
            Invocation.getter(#nwc),
            returnValue: _FakeNwc_13(this, Invocation.getter(#nwc)),
          )
          as _i9.Nwc);

  @override
  _i2.Ndk get ndk =>
      (super.noSuchMethod(
            Invocation.getter(#ndk),
            returnValue: _FakeNdk_0(this, Invocation.getter(#ndk)),
          )
          as _i2.Ndk);

  @override
  set nwc(_i9.Nwc? value) => super.noSuchMethod(
    Invocation.setter(#nwc, value),
    returnValueForMissingStub: null,
  );

  @override
  set ndk(_i2.Ndk? value) => super.noSuchMethod(
    Invocation.setter(#ndk, value),
    returnValueForMissingStub: null,
  );

  @override
  _i24.Future<_i2.ZapResponse> zap({
    required String? lnurl,
    required int? amountSats,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#zap, [], {
              #lnurl: lnurl,
              #amountSats: amountSats,
            }),
            returnValue: _i24.Future<_i2.ZapResponse>.value(
              _FakeZapResponse_14(
                this,
                Invocation.method(#zap, [], {
                  #lnurl: lnurl,
                  #amountSats: amountSats,
                }),
              ),
            ),
          )
          as _i24.Future<_i2.ZapResponse>);

  @override
  _i24.Future<_i2.InvoiceResponse?> fetchInvoice({
    required String? lud16Link,
    required int? amountSats,
    _i2.ZapRequest? zapRequest,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchInvoice, [], {
              #lud16Link: lud16Link,
              #amountSats: amountSats,
              #zapRequest: zapRequest,
            }),
            returnValue: _i24.Future<_i2.InvoiceResponse?>.value(),
          )
          as _i24.Future<_i2.InvoiceResponse?>);
}

/// A class which mocks [Listings].
///
/// See the documentation for Mockito's code generation for more information.
class MockListings extends _i1.Mock implements _i28.Listings {
  MockListings() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_7(this, Invocation.getter(#logger)),
          )
          as _i6.CustomLogger);

  @override
  _i7.Requests get requests =>
      (super.noSuchMethod(
            Invocation.getter(#requests),
            returnValue: _FakeRequests_5(this, Invocation.getter(#requests)),
          )
          as _i7.Requests);

  @override
  int get kind =>
      (super.noSuchMethod(Invocation.getter(#kind), returnValue: 0) as int);

  @override
  _i24.Future<List<_i25.RelayBroadcastResponse>> create(_i10.Listing? event) =>
      (super.noSuchMethod(
            Invocation.method(#create, [event]),
            returnValue: _i24.Future<List<_i25.RelayBroadcastResponse>>.value(
              <_i25.RelayBroadcastResponse>[],
            ),
          )
          as _i24.Future<List<_i25.RelayBroadcastResponse>>);

  @override
  _i24.Future<List<_i25.RelayBroadcastResponse>> update(_i10.Listing? event) =>
      (super.noSuchMethod(
            Invocation.method(#update, [event]),
            returnValue: _i24.Future<List<_i25.RelayBroadcastResponse>>.value(
              <_i25.RelayBroadcastResponse>[],
            ),
          )
          as _i24.Future<List<_i25.RelayBroadcastResponse>>);

  @override
  _i24.Future<List<_i25.RelayBroadcastResponse>> delete(_i10.Listing? event) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [event]),
            returnValue: _i24.Future<List<_i25.RelayBroadcastResponse>>.value(
              <_i25.RelayBroadcastResponse>[],
            ),
          )
          as _i24.Future<List<_i25.RelayBroadcastResponse>>);

  @override
  _i24.Future<List<_i10.Listing>> list(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#list, [f]),
            returnValue: _i24.Future<List<_i10.Listing>>.value(
              <_i10.Listing>[],
            ),
          )
          as _i24.Future<List<_i10.Listing>>);

  @override
  _i24.Future<_i10.Listing?> getOne(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#getOne, [f]),
            returnValue: _i24.Future<_i10.Listing?>.value(),
          )
          as _i24.Future<_i10.Listing?>);

  @override
  _i24.Future<_i10.Listing> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i24.Future<_i10.Listing>.value(
              _FakeListing_15(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i24.Future<_i10.Listing>);

  @override
  _i24.Future<int> count() =>
      (super.noSuchMethod(
            Invocation.method(#count, []),
            returnValue: _i24.Future<int>.value(0),
          )
          as _i24.Future<int>);
}

/// A class which mocks [Reservations].
///
/// See the documentation for Mockito's code generation for more information.
class MockReservations extends _i1.Mock implements _i29.Reservations {
  MockReservations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Messaging get messaging =>
      (super.noSuchMethod(
            Invocation.getter(#messaging),
            returnValue: _FakeMessaging_16(this, Invocation.getter(#messaging)),
          )
          as _i11.Messaging);

  @override
  _i8.Auth get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeAuth_6(this, Invocation.getter(#auth)),
          )
          as _i8.Auth);

  @override
  _i6.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_7(this, Invocation.getter(#logger)),
          )
          as _i6.CustomLogger);

  @override
  _i7.Requests get requests =>
      (super.noSuchMethod(
            Invocation.getter(#requests),
            returnValue: _FakeRequests_5(this, Invocation.getter(#requests)),
          )
          as _i7.Requests);

  @override
  int get kind =>
      (super.noSuchMethod(Invocation.getter(#kind), returnValue: 0) as int);

  @override
  _i24.Future<List<_i10.Reservation>> getListingReservations({
    required String? listingAnchor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getListingReservations, [], {
              #listingAnchor: listingAnchor,
            }),
            returnValue: _i24.Future<List<_i10.Reservation>>.value(
              <_i10.Reservation>[],
            ),
          )
          as _i24.Future<List<_i10.Reservation>>);

  @override
  _i6.StreamWithStatus<_i10.Reservation> subscribeToMyReservations() =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToMyReservations, []),
            returnValue: _FakeStreamWithStatus_4<_i10.Reservation>(
              this,
              Invocation.method(#subscribeToMyReservations, []),
            ),
          )
          as _i6.StreamWithStatus<_i10.Reservation>);

  @override
  _i24.Future<List<_i25.RelayBroadcastResponse>> accept(
    _i10.Message<_i10.Event>? message,
    _i10.ReservationRequest? request,
    String? guestPubkey,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#accept, [message, request, guestPubkey]),
            returnValue: _i24.Future<List<_i25.RelayBroadcastResponse>>.value(
              <_i25.RelayBroadcastResponse>[],
            ),
          )
          as _i24.Future<List<_i25.RelayBroadcastResponse>>);

  @override
  _i24.Future<_i10.Reservation> createSelfSigned({
    required String? threadId,
    required _i10.ReservationRequest? reservationRequest,
    required _i10.Listing? listing,
    required _i10.ProfileMetadata? hoster,
    _i10.ZapProof? zapProof,
    _i10.EscrowProof? escrowProof,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSelfSigned, [], {
              #threadId: threadId,
              #reservationRequest: reservationRequest,
              #listing: listing,
              #hoster: hoster,
              #zapProof: zapProof,
              #escrowProof: escrowProof,
            }),
            returnValue: _i24.Future<_i10.Reservation>.value(
              _FakeReservation_17(
                this,
                Invocation.method(#createSelfSigned, [], {
                  #threadId: threadId,
                  #reservationRequest: reservationRequest,
                  #listing: listing,
                  #hoster: hoster,
                  #zapProof: zapProof,
                  #escrowProof: escrowProof,
                }),
              ),
            ),
          )
          as _i24.Future<_i10.Reservation>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i24.Future<List<_i25.RelayBroadcastResponse>> create(
    _i10.Reservation? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [event]),
            returnValue: _i24.Future<List<_i25.RelayBroadcastResponse>>.value(
              <_i25.RelayBroadcastResponse>[],
            ),
          )
          as _i24.Future<List<_i25.RelayBroadcastResponse>>);

  @override
  _i24.Future<List<_i25.RelayBroadcastResponse>> update(
    _i10.Reservation? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [event]),
            returnValue: _i24.Future<List<_i25.RelayBroadcastResponse>>.value(
              <_i25.RelayBroadcastResponse>[],
            ),
          )
          as _i24.Future<List<_i25.RelayBroadcastResponse>>);

  @override
  _i24.Future<List<_i25.RelayBroadcastResponse>> delete(
    _i10.Reservation? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [event]),
            returnValue: _i24.Future<List<_i25.RelayBroadcastResponse>>.value(
              <_i25.RelayBroadcastResponse>[],
            ),
          )
          as _i24.Future<List<_i25.RelayBroadcastResponse>>);

  @override
  _i24.Future<List<_i10.Reservation>> list(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#list, [f]),
            returnValue: _i24.Future<List<_i10.Reservation>>.value(
              <_i10.Reservation>[],
            ),
          )
          as _i24.Future<List<_i10.Reservation>>);

  @override
  _i24.Future<_i10.Reservation?> getOne(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#getOne, [f]),
            returnValue: _i24.Future<_i10.Reservation?>.value(),
          )
          as _i24.Future<_i10.Reservation?>);

  @override
  _i24.Future<_i10.Reservation> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i24.Future<_i10.Reservation>.value(
              _FakeReservation_17(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i24.Future<_i10.Reservation>);

  @override
  _i24.Future<int> count() =>
      (super.noSuchMethod(
            Invocation.method(#count, []),
            returnValue: _i24.Future<int>.value(0),
          )
          as _i24.Future<int>);
}

/// A class which mocks [EscrowUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEscrowUseCase extends _i1.Mock implements _i30.EscrowUseCase {
  MockEscrowUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_7(this, Invocation.getter(#logger)),
          )
          as _i6.CustomLogger);

  @override
  _i8.Auth get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeAuth_6(this, Invocation.getter(#auth)),
          )
          as _i8.Auth);

  @override
  _i12.Escrows get escrows =>
      (super.noSuchMethod(
            Invocation.getter(#escrows),
            returnValue: _FakeEscrows_18(this, Invocation.getter(#escrows)),
          )
          as _i12.Escrows);

  @override
  _i13.EscrowTrusts get escrowTrusts =>
      (super.noSuchMethod(
            Invocation.getter(#escrowTrusts),
            returnValue: _FakeEscrowTrusts_19(
              this,
              Invocation.getter(#escrowTrusts),
            ),
          )
          as _i13.EscrowTrusts);

  @override
  _i14.Evm get evm =>
      (super.noSuchMethod(
            Invocation.getter(#evm),
            returnValue: _FakeEvm_20(this, Invocation.getter(#evm)),
          )
          as _i14.Evm);

  @override
  _i15.EscrowFundOperation fund(_i31.EscrowFundParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#fund, [params]),
            returnValue: _FakeEscrowFundOperation_21(
              this,
              Invocation.method(#fund, [params]),
            ),
          )
          as _i15.EscrowFundOperation);

  @override
  _i6.StreamWithStatus<_i32.FundedEvent> checkEscrowStatus(
    String? tradeId,
    String? counterpartyPubkey,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkEscrowStatus, [
              tradeId,
              counterpartyPubkey,
            ]),
            returnValue: _FakeStreamWithStatus_4<_i32.FundedEvent>(
              this,
              Invocation.method(#checkEscrowStatus, [
                tradeId,
                counterpartyPubkey,
              ]),
            ),
          )
          as _i6.StreamWithStatus<_i32.FundedEvent>);
}

/// A class which mocks [Escrows].
///
/// See the documentation for Mockito's code generation for more information.
class MockEscrows extends _i1.Mock implements _i12.Escrows {
  MockEscrows() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.EscrowMethods get escrowMethods =>
      (super.noSuchMethod(
            Invocation.getter(#escrowMethods),
            returnValue: _FakeEscrowMethods_22(
              this,
              Invocation.getter(#escrowMethods),
            ),
          )
          as _i16.EscrowMethods);

  @override
  _i13.EscrowTrusts get escrowTrusts =>
      (super.noSuchMethod(
            Invocation.getter(#escrowTrusts),
            returnValue: _FakeEscrowTrusts_19(
              this,
              Invocation.getter(#escrowTrusts),
            ),
          )
          as _i13.EscrowTrusts);

  @override
  set escrowMethods(_i16.EscrowMethods? value) => super.noSuchMethod(
    Invocation.setter(#escrowMethods, value),
    returnValueForMissingStub: null,
  );

  @override
  set escrowTrusts(_i13.EscrowTrusts? value) => super.noSuchMethod(
    Invocation.setter(#escrowTrusts, value),
    returnValueForMissingStub: null,
  );

  @override
  _i6.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_7(this, Invocation.getter(#logger)),
          )
          as _i6.CustomLogger);

  @override
  _i7.Requests get requests =>
      (super.noSuchMethod(
            Invocation.getter(#requests),
            returnValue: _FakeRequests_5(this, Invocation.getter(#requests)),
          )
          as _i7.Requests);

  @override
  int get kind =>
      (super.noSuchMethod(Invocation.getter(#kind), returnValue: 0) as int);

  @override
  _i24.Future<_i12.MutualEscrowResult> determineMutualEscrow(
    String? pubkey1,
    String? pubkey2,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#determineMutualEscrow, [pubkey1, pubkey2]),
            returnValue: _i24.Future<_i12.MutualEscrowResult>.value(
              _FakeMutualEscrowResult_23(
                this,
                Invocation.method(#determineMutualEscrow, [pubkey1, pubkey2]),
              ),
            ),
          )
          as _i24.Future<_i12.MutualEscrowResult>);

  @override
  _i24.Future<List<_i25.RelayBroadcastResponse>> create(
    _i10.EscrowService? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [event]),
            returnValue: _i24.Future<List<_i25.RelayBroadcastResponse>>.value(
              <_i25.RelayBroadcastResponse>[],
            ),
          )
          as _i24.Future<List<_i25.RelayBroadcastResponse>>);

  @override
  _i24.Future<List<_i25.RelayBroadcastResponse>> update(
    _i10.EscrowService? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [event]),
            returnValue: _i24.Future<List<_i25.RelayBroadcastResponse>>.value(
              <_i25.RelayBroadcastResponse>[],
            ),
          )
          as _i24.Future<List<_i25.RelayBroadcastResponse>>);

  @override
  _i24.Future<List<_i25.RelayBroadcastResponse>> delete(
    _i10.EscrowService? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [event]),
            returnValue: _i24.Future<List<_i25.RelayBroadcastResponse>>.value(
              <_i25.RelayBroadcastResponse>[],
            ),
          )
          as _i24.Future<List<_i25.RelayBroadcastResponse>>);

  @override
  _i24.Future<List<_i10.EscrowService>> list(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#list, [f]),
            returnValue: _i24.Future<List<_i10.EscrowService>>.value(
              <_i10.EscrowService>[],
            ),
          )
          as _i24.Future<List<_i10.EscrowService>>);

  @override
  _i24.Future<_i10.EscrowService?> getOne(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#getOne, [f]),
            returnValue: _i24.Future<_i10.EscrowService?>.value(),
          )
          as _i24.Future<_i10.EscrowService?>);

  @override
  _i24.Future<_i10.EscrowService> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i24.Future<_i10.EscrowService>.value(
              _FakeEscrowService_24(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i24.Future<_i10.EscrowService>);

  @override
  _i24.Future<int> count() =>
      (super.noSuchMethod(
            Invocation.method(#count, []),
            returnValue: _i24.Future<int>.value(0),
          )
          as _i24.Future<int>);
}

/// A class which mocks [EscrowTrusts].
///
/// See the documentation for Mockito's code generation for more information.
class MockEscrowTrusts extends _i1.Mock implements _i13.EscrowTrusts {
  MockEscrowTrusts() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Auth get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeAuth_6(this, Invocation.getter(#auth)),
          )
          as _i8.Auth);

  @override
  _i6.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_7(this, Invocation.getter(#logger)),
          )
          as _i6.CustomLogger);

  @override
  _i7.Requests get requests =>
      (super.noSuchMethod(
            Invocation.getter(#requests),
            returnValue: _FakeRequests_5(this, Invocation.getter(#requests)),
          )
          as _i7.Requests);

  @override
  int get kind =>
      (super.noSuchMethod(Invocation.getter(#kind), returnValue: 0) as int);

  @override
  _i24.Future<_i10.EscrowTrust?> trusted(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#trusted, [pubkey]),
            returnValue: _i24.Future<_i10.EscrowTrust?>.value(),
          )
          as _i24.Future<_i10.EscrowTrust?>);

  @override
  _i24.Future<_i10.EscrowTrust?> myTrusted() =>
      (super.noSuchMethod(
            Invocation.method(#myTrusted, []),
            returnValue: _i24.Future<_i10.EscrowTrust?>.value(),
          )
          as _i24.Future<_i10.EscrowTrust?>);

  @override
  _i24.Future<List<_i25.RelayBroadcastResponse>> create(
    _i10.EscrowTrust? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [event]),
            returnValue: _i24.Future<List<_i25.RelayBroadcastResponse>>.value(
              <_i25.RelayBroadcastResponse>[],
            ),
          )
          as _i24.Future<List<_i25.RelayBroadcastResponse>>);

  @override
  _i24.Future<List<_i25.RelayBroadcastResponse>> update(
    _i10.EscrowTrust? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [event]),
            returnValue: _i24.Future<List<_i25.RelayBroadcastResponse>>.value(
              <_i25.RelayBroadcastResponse>[],
            ),
          )
          as _i24.Future<List<_i25.RelayBroadcastResponse>>);

  @override
  _i24.Future<List<_i25.RelayBroadcastResponse>> delete(
    _i10.EscrowTrust? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [event]),
            returnValue: _i24.Future<List<_i25.RelayBroadcastResponse>>.value(
              <_i25.RelayBroadcastResponse>[],
            ),
          )
          as _i24.Future<List<_i25.RelayBroadcastResponse>>);

  @override
  _i24.Future<List<_i10.EscrowTrust>> list(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#list, [f]),
            returnValue: _i24.Future<List<_i10.EscrowTrust>>.value(
              <_i10.EscrowTrust>[],
            ),
          )
          as _i24.Future<List<_i10.EscrowTrust>>);

  @override
  _i24.Future<_i10.EscrowTrust?> getOne(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#getOne, [f]),
            returnValue: _i24.Future<_i10.EscrowTrust?>.value(),
          )
          as _i24.Future<_i10.EscrowTrust?>);

  @override
  _i24.Future<_i10.EscrowTrust> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i24.Future<_i10.EscrowTrust>.value(
              _FakeEscrowTrust_25(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i24.Future<_i10.EscrowTrust>);

  @override
  _i24.Future<int> count() =>
      (super.noSuchMethod(
            Invocation.method(#count, []),
            returnValue: _i24.Future<int>.value(0),
          )
          as _i24.Future<int>);
}

/// A class which mocks [EscrowMethods].
///
/// See the documentation for Mockito's code generation for more information.
class MockEscrowMethods extends _i1.Mock implements _i16.EscrowMethods {
  MockEscrowMethods() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_7(this, Invocation.getter(#logger)),
          )
          as _i6.CustomLogger);

  @override
  _i7.Requests get requests =>
      (super.noSuchMethod(
            Invocation.getter(#requests),
            returnValue: _FakeRequests_5(this, Invocation.getter(#requests)),
          )
          as _i7.Requests);

  @override
  int get kind =>
      (super.noSuchMethod(Invocation.getter(#kind), returnValue: 0) as int);

  @override
  _i24.Future<List<_i25.RelayBroadcastResponse>> create(
    _i10.EscrowMethod? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [event]),
            returnValue: _i24.Future<List<_i25.RelayBroadcastResponse>>.value(
              <_i25.RelayBroadcastResponse>[],
            ),
          )
          as _i24.Future<List<_i25.RelayBroadcastResponse>>);

  @override
  _i24.Future<List<_i25.RelayBroadcastResponse>> update(
    _i10.EscrowMethod? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [event]),
            returnValue: _i24.Future<List<_i25.RelayBroadcastResponse>>.value(
              <_i25.RelayBroadcastResponse>[],
            ),
          )
          as _i24.Future<List<_i25.RelayBroadcastResponse>>);

  @override
  _i24.Future<List<_i25.RelayBroadcastResponse>> delete(
    _i10.EscrowMethod? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [event]),
            returnValue: _i24.Future<List<_i25.RelayBroadcastResponse>>.value(
              <_i25.RelayBroadcastResponse>[],
            ),
          )
          as _i24.Future<List<_i25.RelayBroadcastResponse>>);

  @override
  _i24.Future<List<_i10.EscrowMethod>> list(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#list, [f]),
            returnValue: _i24.Future<List<_i10.EscrowMethod>>.value(
              <_i10.EscrowMethod>[],
            ),
          )
          as _i24.Future<List<_i10.EscrowMethod>>);

  @override
  _i24.Future<_i10.EscrowMethod?> getOne(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#getOne, [f]),
            returnValue: _i24.Future<_i10.EscrowMethod?>.value(),
          )
          as _i24.Future<_i10.EscrowMethod?>);

  @override
  _i24.Future<_i10.EscrowMethod> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i24.Future<_i10.EscrowMethod>.value(
              _FakeEscrowMethod_26(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i24.Future<_i10.EscrowMethod>);

  @override
  _i24.Future<int> count() =>
      (super.noSuchMethod(
            Invocation.method(#count, []),
            returnValue: _i24.Future<int>.value(0),
          )
          as _i24.Future<int>);
}

/// A class which mocks [BadgeDefinitions].
///
/// See the documentation for Mockito's code generation for more information.
class MockBadgeDefinitions extends _i1.Mock implements _i33.BadgeDefinitions {
  MockBadgeDefinitions() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_7(this, Invocation.getter(#logger)),
          )
          as _i6.CustomLogger);

  @override
  _i7.Requests get requests =>
      (super.noSuchMethod(
            Invocation.getter(#requests),
            returnValue: _FakeRequests_5(this, Invocation.getter(#requests)),
          )
          as _i7.Requests);

  @override
  int get kind =>
      (super.noSuchMethod(Invocation.getter(#kind), returnValue: 0) as int);

  @override
  _i24.Future<List<_i25.RelayBroadcastResponse>> create(
    _i10.BadgeDefinition? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [event]),
            returnValue: _i24.Future<List<_i25.RelayBroadcastResponse>>.value(
              <_i25.RelayBroadcastResponse>[],
            ),
          )
          as _i24.Future<List<_i25.RelayBroadcastResponse>>);

  @override
  _i24.Future<List<_i25.RelayBroadcastResponse>> update(
    _i10.BadgeDefinition? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [event]),
            returnValue: _i24.Future<List<_i25.RelayBroadcastResponse>>.value(
              <_i25.RelayBroadcastResponse>[],
            ),
          )
          as _i24.Future<List<_i25.RelayBroadcastResponse>>);

  @override
  _i24.Future<List<_i25.RelayBroadcastResponse>> delete(
    _i10.BadgeDefinition? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [event]),
            returnValue: _i24.Future<List<_i25.RelayBroadcastResponse>>.value(
              <_i25.RelayBroadcastResponse>[],
            ),
          )
          as _i24.Future<List<_i25.RelayBroadcastResponse>>);

  @override
  _i24.Future<List<_i10.BadgeDefinition>> list(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#list, [f]),
            returnValue: _i24.Future<List<_i10.BadgeDefinition>>.value(
              <_i10.BadgeDefinition>[],
            ),
          )
          as _i24.Future<List<_i10.BadgeDefinition>>);

  @override
  _i24.Future<_i10.BadgeDefinition?> getOne(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#getOne, [f]),
            returnValue: _i24.Future<_i10.BadgeDefinition?>.value(),
          )
          as _i24.Future<_i10.BadgeDefinition?>);

  @override
  _i24.Future<_i10.BadgeDefinition> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i24.Future<_i10.BadgeDefinition>.value(
              _FakeBadgeDefinition_27(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i24.Future<_i10.BadgeDefinition>);

  @override
  _i24.Future<int> count() =>
      (super.noSuchMethod(
            Invocation.method(#count, []),
            returnValue: _i24.Future<int>.value(0),
          )
          as _i24.Future<int>);
}

/// A class which mocks [BadgeAwards].
///
/// See the documentation for Mockito's code generation for more information.
class MockBadgeAwards extends _i1.Mock implements _i34.BadgeAwards {
  MockBadgeAwards() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_7(this, Invocation.getter(#logger)),
          )
          as _i6.CustomLogger);

  @override
  _i7.Requests get requests =>
      (super.noSuchMethod(
            Invocation.getter(#requests),
            returnValue: _FakeRequests_5(this, Invocation.getter(#requests)),
          )
          as _i7.Requests);

  @override
  int get kind =>
      (super.noSuchMethod(Invocation.getter(#kind), returnValue: 0) as int);

  @override
  _i24.Future<List<_i25.RelayBroadcastResponse>> create(
    _i10.BadgeAward? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [event]),
            returnValue: _i24.Future<List<_i25.RelayBroadcastResponse>>.value(
              <_i25.RelayBroadcastResponse>[],
            ),
          )
          as _i24.Future<List<_i25.RelayBroadcastResponse>>);

  @override
  _i24.Future<List<_i25.RelayBroadcastResponse>> update(
    _i10.BadgeAward? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [event]),
            returnValue: _i24.Future<List<_i25.RelayBroadcastResponse>>.value(
              <_i25.RelayBroadcastResponse>[],
            ),
          )
          as _i24.Future<List<_i25.RelayBroadcastResponse>>);

  @override
  _i24.Future<List<_i25.RelayBroadcastResponse>> delete(
    _i10.BadgeAward? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [event]),
            returnValue: _i24.Future<List<_i25.RelayBroadcastResponse>>.value(
              <_i25.RelayBroadcastResponse>[],
            ),
          )
          as _i24.Future<List<_i25.RelayBroadcastResponse>>);

  @override
  _i24.Future<List<_i10.BadgeAward>> list(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#list, [f]),
            returnValue: _i24.Future<List<_i10.BadgeAward>>.value(
              <_i10.BadgeAward>[],
            ),
          )
          as _i24.Future<List<_i10.BadgeAward>>);

  @override
  _i24.Future<_i10.BadgeAward?> getOne(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#getOne, [f]),
            returnValue: _i24.Future<_i10.BadgeAward?>.value(),
          )
          as _i24.Future<_i10.BadgeAward?>);

  @override
  _i24.Future<_i10.BadgeAward> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i24.Future<_i10.BadgeAward>.value(
              _FakeBadgeAward_28(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i24.Future<_i10.BadgeAward>);

  @override
  _i24.Future<int> count() =>
      (super.noSuchMethod(
            Invocation.method(#count, []),
            returnValue: _i24.Future<int>.value(0),
          )
          as _i24.Future<int>);
}

/// A class which mocks [Messaging].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessaging extends _i1.Mock implements _i11.Messaging {
  MockMessaging() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Ndk get ndk =>
      (super.noSuchMethod(
            Invocation.getter(#ndk),
            returnValue: _FakeNdk_0(this, Invocation.getter(#ndk)),
          )
          as _i2.Ndk);

  @override
  _i7.Requests get requests =>
      (super.noSuchMethod(
            Invocation.getter(#requests),
            returnValue: _FakeRequests_5(this, Invocation.getter(#requests)),
          )
          as _i7.Requests);

  @override
  _i6.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_7(this, Invocation.getter(#logger)),
          )
          as _i6.CustomLogger);

  @override
  _i17.Threads get threads =>
      (super.noSuchMethod(
            Invocation.getter(#threads),
            returnValue: _FakeThreads_29(this, Invocation.getter(#threads)),
          )
          as _i17.Threads);

  @override
  _i24.Future<_i2.Nip01Event> getRumour(
    String? content,
    List<List<String>>? tags,
    List<String>? recipientPubkeys,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRumour, [content, tags, recipientPubkeys]),
            returnValue: _i24.Future<_i2.Nip01Event>.value(
              _FakeNip01Event_30(
                this,
                Invocation.method(#getRumour, [
                  content,
                  tags,
                  recipientPubkeys,
                ]),
              ),
            ),
          )
          as _i24.Future<_i2.Nip01Event>);

  @override
  _i24.Future<_i10.Message<_i10.Event>> broadcastTextAndAwait({
    required String? content,
    required List<List<String>>? tags,
    required List<String>? recipientPubkeys,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastTextAndAwait, [], {
              #content: content,
              #tags: tags,
              #recipientPubkeys: recipientPubkeys,
            }),
            returnValue: _i24.Future<_i10.Message<_i10.Event>>.value(
              _FakeMessage_31<_i10.Event>(
                this,
                Invocation.method(#broadcastTextAndAwait, [], {
                  #content: content,
                  #tags: tags,
                  #recipientPubkeys: recipientPubkeys,
                }),
              ),
            ),
          )
          as _i24.Future<_i10.Message<_i10.Event>>);

  @override
  _i24.Future<List<_i24.Future<List<_i25.RelayBroadcastResponse>>>>
  broadcastText({
    required String? content,
    required List<List<String>>? tags,
    required List<String>? recipientPubkeys,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastText, [], {
              #content: content,
              #tags: tags,
              #recipientPubkeys: recipientPubkeys,
            }),
            returnValue:
                _i24.Future<
                  List<_i24.Future<List<_i25.RelayBroadcastResponse>>>
                >.value(<_i24.Future<List<_i25.RelayBroadcastResponse>>>[]),
          )
          as _i24.Future<List<_i24.Future<List<_i25.RelayBroadcastResponse>>>>);

  @override
  _i24.Future<_i10.Message<_i10.Event>> broadcastEventAndWait({
    required _i2.Nip01Event? event,
    required List<List<String>>? tags,
    required List<String>? recipientPubkeys,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastEventAndWait, [], {
              #event: event,
              #tags: tags,
              #recipientPubkeys: recipientPubkeys,
            }),
            returnValue: _i24.Future<_i10.Message<_i10.Event>>.value(
              _FakeMessage_31<_i10.Event>(
                this,
                Invocation.method(#broadcastEventAndWait, [], {
                  #event: event,
                  #tags: tags,
                  #recipientPubkeys: recipientPubkeys,
                }),
              ),
            ),
          )
          as _i24.Future<_i10.Message<_i10.Event>>);

  @override
  _i24.Future<List<_i24.Future<List<_i25.RelayBroadcastResponse>>>>
  broadcastEvent({
    required _i2.Nip01Event? event,
    required List<List<String>>? tags,
    required List<String>? recipientPubkeys,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastEvent, [], {
              #event: event,
              #tags: tags,
              #recipientPubkeys: recipientPubkeys,
            }),
            returnValue:
                _i24.Future<
                  List<_i24.Future<List<_i25.RelayBroadcastResponse>>>
                >.value(<_i24.Future<List<_i25.RelayBroadcastResponse>>>[]),
          )
          as _i24.Future<List<_i24.Future<List<_i25.RelayBroadcastResponse>>>>);
}

/// A class which mocks [ReservationRequests].
///
/// See the documentation for Mockito's code generation for more information.
class MockReservationRequests extends _i1.Mock
    implements _i35.ReservationRequests {
  MockReservationRequests() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Ndk get ndk =>
      (super.noSuchMethod(
            Invocation.getter(#ndk),
            returnValue: _FakeNdk_0(this, Invocation.getter(#ndk)),
          )
          as _i2.Ndk);

  @override
  _i6.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_7(this, Invocation.getter(#logger)),
          )
          as _i6.CustomLogger);

  @override
  _i7.Requests get requests =>
      (super.noSuchMethod(
            Invocation.getter(#requests),
            returnValue: _FakeRequests_5(this, Invocation.getter(#requests)),
          )
          as _i7.Requests);

  @override
  int get kind =>
      (super.noSuchMethod(Invocation.getter(#kind), returnValue: 0) as int);

  @override
  _i24.Future<_i10.ReservationRequest> createReservationRequest({
    required _i10.Listing? listing,
    required DateTime? startDate,
    required DateTime? endDate,
    required String? recipientPubkey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createReservationRequest, [], {
              #listing: listing,
              #startDate: startDate,
              #endDate: endDate,
              #recipientPubkey: recipientPubkey,
            }),
            returnValue: _i24.Future<_i10.ReservationRequest>.value(
              _FakeReservationRequest_32(
                this,
                Invocation.method(#createReservationRequest, [], {
                  #listing: listing,
                  #startDate: startDate,
                  #endDate: endDate,
                  #recipientPubkey: recipientPubkey,
                }),
              ),
            ),
          )
          as _i24.Future<_i10.ReservationRequest>);

  @override
  _i24.Future<List<_i25.RelayBroadcastResponse>> create(
    _i2.Nip01Event? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [event]),
            returnValue: _i24.Future<List<_i25.RelayBroadcastResponse>>.value(
              <_i25.RelayBroadcastResponse>[],
            ),
          )
          as _i24.Future<List<_i25.RelayBroadcastResponse>>);

  @override
  _i24.Future<List<_i25.RelayBroadcastResponse>> update(
    _i2.Nip01Event? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [event]),
            returnValue: _i24.Future<List<_i25.RelayBroadcastResponse>>.value(
              <_i25.RelayBroadcastResponse>[],
            ),
          )
          as _i24.Future<List<_i25.RelayBroadcastResponse>>);

  @override
  _i24.Future<List<_i25.RelayBroadcastResponse>> delete(
    _i2.Nip01Event? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [event]),
            returnValue: _i24.Future<List<_i25.RelayBroadcastResponse>>.value(
              <_i25.RelayBroadcastResponse>[],
            ),
          )
          as _i24.Future<List<_i25.RelayBroadcastResponse>>);

  @override
  _i24.Future<List<_i2.Nip01Event>> list(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#list, [f]),
            returnValue: _i24.Future<List<_i2.Nip01Event>>.value(
              <_i2.Nip01Event>[],
            ),
          )
          as _i24.Future<List<_i2.Nip01Event>>);

  @override
  _i24.Future<_i2.Nip01Event?> getOne(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#getOne, [f]),
            returnValue: _i24.Future<_i2.Nip01Event?>.value(),
          )
          as _i24.Future<_i2.Nip01Event?>);

  @override
  _i24.Future<_i2.Nip01Event> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i24.Future<_i2.Nip01Event>.value(
              _FakeNip01Event_30(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i24.Future<_i2.Nip01Event>);

  @override
  _i24.Future<int> count() =>
      (super.noSuchMethod(
            Invocation.method(#count, []),
            returnValue: _i24.Future<int>.value(0),
          )
          as _i24.Future<int>);
}

/// A class which mocks [Payments].
///
/// See the documentation for Mockito's code generation for more information.
class MockPayments extends _i1.Mock implements _i36.Payments {
  MockPayments() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_7(this, Invocation.getter(#logger)),
          )
          as _i6.CustomLogger);

  @override
  _i18.Zaps get zaps =>
      (super.noSuchMethod(
            Invocation.getter(#zaps),
            returnValue: _FakeZaps_33(this, Invocation.getter(#zaps)),
          )
          as _i18.Zaps);

  @override
  _i9.Nwc get nwc =>
      (super.noSuchMethod(
            Invocation.getter(#nwc),
            returnValue: _FakeNwc_13(this, Invocation.getter(#nwc)),
          )
          as _i9.Nwc);

  @override
  set zaps(_i18.Zaps? value) => super.noSuchMethod(
    Invocation.setter(#zaps, value),
    returnValueForMissingStub: null,
  );

  @override
  set nwc(_i9.Nwc? value) => super.noSuchMethod(
    Invocation.setter(#nwc, value),
    returnValueForMissingStub: null,
  );

  @override
  _i20.PayOperation<
    _i19.PayParameters,
    _i19.ResolvedDetails,
    _i19.CallbackDetails,
    _i19.CompletedDetails
  >
  pay(_i19.PayParameters? params) =>
      (super.noSuchMethod(
            Invocation.method(#pay, [params]),
            returnValue:
                _FakePayOperation_34<
                  _i19.PayParameters,
                  _i19.ResolvedDetails,
                  _i19.CallbackDetails,
                  _i19.CompletedDetails
                >(this, Invocation.method(#pay, [params])),
          )
          as _i20.PayOperation<
            _i19.PayParameters,
            _i19.ResolvedDetails,
            _i19.CallbackDetails,
            _i19.CompletedDetails
          >);
}

/// A class which mocks [Evm].
///
/// See the documentation for Mockito's code generation for more information.
class MockEvm extends _i1.Mock implements _i14.Evm {
  MockEvm() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_7(this, Invocation.getter(#logger)),
          )
          as _i6.CustomLogger);

  @override
  _i8.Auth get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeAuth_6(this, Invocation.getter(#auth)),
          )
          as _i8.Auth);

  @override
  _i21.Rootstock get rootstock =>
      (super.noSuchMethod(
            Invocation.getter(#rootstock),
            returnValue: _FakeRootstock_35(this, Invocation.getter(#rootstock)),
          )
          as _i21.Rootstock);

  @override
  List<_i22.EvmChain> get supportedEvmChains =>
      (super.noSuchMethod(
            Invocation.getter(#supportedEvmChains),
            returnValue: <_i22.EvmChain>[],
          )
          as List<_i22.EvmChain>);

  @override
  set supportedEvmChains(List<_i22.EvmChain>? value) => super.noSuchMethod(
    Invocation.setter(#supportedEvmChains, value),
    returnValueForMissingStub: null,
  );

  @override
  _i24.Future<_i6.BitcoinAmount> getBalance() =>
      (super.noSuchMethod(
            Invocation.method(#getBalance, []),
            returnValue: _i24.Future<_i6.BitcoinAmount>.value(
              _FakeBitcoinAmount_36(this, Invocation.method(#getBalance, [])),
            ),
          )
          as _i24.Future<_i6.BitcoinAmount>);

  @override
  _i22.EvmChain getChainForEscrowService(_i10.EscrowService? service) =>
      (super.noSuchMethod(
            Invocation.method(#getChainForEscrowService, [service]),
            returnValue: _FakeEvmChain_37(
              this,
              Invocation.method(#getChainForEscrowService, [service]),
            ),
          )
          as _i22.EvmChain);

  @override
  _i4.ValueStream<_i6.BitcoinAmount> subscribeBalance() =>
      (super.noSuchMethod(
            Invocation.method(#subscribeBalance, []),
            returnValue: _FakeValueStream_2<_i6.BitcoinAmount>(
              this,
              Invocation.method(#subscribeBalance, []),
            ),
          )
          as _i4.ValueStream<_i6.BitcoinAmount>);

  @override
  _i24.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i24.Future<void>.value(),
            returnValueForMissingStub: _i24.Future<void>.value(),
          )
          as _i24.Future<void>);

  @override
  _i24.Future<_i22.EvmChain> getClientForChainId(int? chainId) =>
      (super.noSuchMethod(
            Invocation.method(#getClientForChainId, [chainId]),
            returnValue: _i24.Future<_i22.EvmChain>.value(
              _FakeEvmChain_37(
                this,
                Invocation.method(#getClientForChainId, [chainId]),
              ),
            ),
          )
          as _i24.Future<_i22.EvmChain>);
}

/// A class which mocks [Relays].
///
/// See the documentation for Mockito's code generation for more information.
class MockRelays extends _i1.Mock implements _i37.Relays {
  MockRelays() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_7(this, Invocation.getter(#logger)),
          )
          as _i6.CustomLogger);

  @override
  _i2.Ndk get ndk =>
      (super.noSuchMethod(
            Invocation.getter(#ndk),
            returnValue: _FakeNdk_0(this, Invocation.getter(#ndk)),
          )
          as _i2.Ndk);

  @override
  _i3.RelayStorage get relayStorage =>
      (super.noSuchMethod(
            Invocation.getter(#relayStorage),
            returnValue: _FakeRelayStorage_38(
              this,
              Invocation.getter(#relayStorage),
            ),
          )
          as _i3.RelayStorage);

  @override
  _i24.Future<void> add(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#add, [url]),
            returnValue: _i24.Future<void>.value(),
            returnValueForMissingStub: _i24.Future<void>.value(),
          )
          as _i24.Future<void>);

  @override
  _i24.Future<void> remove(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [url]),
            returnValue: _i24.Future<void>.value(),
            returnValueForMissingStub: _i24.Future<void>.value(),
          )
          as _i24.Future<void>);

  @override
  _i24.Future<void> connect() =>
      (super.noSuchMethod(
            Invocation.method(#connect, []),
            returnValue: _i24.Future<void>.value(),
            returnValueForMissingStub: _i24.Future<void>.value(),
          )
          as _i24.Future<void>);

  @override
  _i24.Stream<Map<String, _i25.RelayConnectivity<dynamic>>> connectivity() =>
      (super.noSuchMethod(
            Invocation.method(#connectivity, []),
            returnValue:
                _i24.Stream<
                  Map<String, _i25.RelayConnectivity<dynamic>>
                >.empty(),
          )
          as _i24.Stream<Map<String, _i25.RelayConnectivity<dynamic>>>);
}
