// Mocks generated by Mockito 5.4.6 from annotations
// in hostr_sdk/mocks/usecase_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;

import 'package:hostr_sdk/hostr_sdk.dart' as _i8;
import 'package:hostr_sdk/usecase/escrow/supported_escrow_contract/supported_escrow_contract.dart'
    as _i15;
import 'package:hostr_sdk/usecase/nwc/nwc.cubit.dart' as _i14;
import 'package:hostr_sdk/usecase/payments/operations/pay_models.dart' as _i10;
import 'package:hostr_sdk/usecase/payments/operations/pay_operation.dart'
    as _i11;
import 'package:hostr_sdk/usecase/storage/storage.dart' as _i3;
import 'package:hostr_sdk/util/main.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:models/main.dart' as _i9;
import 'package:ndk/entities.dart' as _i13;
import 'package:ndk/ndk.dart' as _i2;
import 'package:ndk/shared/nips/nip01/key_pair.dart' as _i5;
import 'package:rxdart/rxdart.dart' as _i4;
import 'package:web3dart/web3dart.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNdk_0 extends _i1.SmartFake implements _i2.Ndk {
  _FakeNdk_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthStorage_1 extends _i1.SmartFake implements _i3.AuthStorage {
  _FakeAuthStorage_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValueStream_2<T> extends _i1.SmartFake
    implements _i4.ValueStream<T> {
  _FakeValueStream_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKeyPair_3 extends _i1.SmartFake implements _i5.KeyPair {
  _FakeKeyPair_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEthPrivateKey_4 extends _i1.SmartFake implements _i6.EthPrivateKey {
  _FakeEthPrivateKey_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamWithStatus_5<T1> extends _i1.SmartFake
    implements _i7.StreamWithStatus<T1> {
  _FakeStreamWithStatus_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuth_6 extends _i1.SmartFake implements _i8.Auth {
  _FakeAuth_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCustomLogger_7 extends _i1.SmartFake implements _i7.CustomLogger {
  _FakeCustomLogger_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRequests_8 extends _i1.SmartFake implements _i8.Requests {
  _FakeRequests_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfileMetadata_9 extends _i1.SmartFake
    implements _i9.ProfileMetadata {
  _FakeProfileMetadata_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNwcStorage_10 extends _i1.SmartFake implements _i3.NwcStorage {
  _FakeNwcStorage_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNwcConnection_11 extends _i1.SmartFake implements _i2.NwcConnection {
  _FakeNwcConnection_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetInfoResponse_12 extends _i1.SmartFake
    implements _i2.GetInfoResponse {
  _FakeGetInfoResponse_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePayInvoiceResponse_13 extends _i1.SmartFake
    implements _i2.PayInvoiceResponse {
  _FakePayInvoiceResponse_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMakeInvoiceResponse_14 extends _i1.SmartFake
    implements _i2.MakeInvoiceResponse {
  _FakeMakeInvoiceResponse_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLookupInvoiceResponse_15 extends _i1.SmartFake
    implements _i2.LookupInvoiceResponse {
  _FakeLookupInvoiceResponse_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNwc_16 extends _i1.SmartFake implements _i8.Nwc {
  _FakeNwc_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeZapResponse_17 extends _i1.SmartFake implements _i2.ZapResponse {
  _FakeZapResponse_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeListing_18 extends _i1.SmartFake implements _i9.Listing {
  _FakeListing_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessaging_19 extends _i1.SmartFake implements _i8.Messaging {
  _FakeMessaging_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValidatedStreamWithStatus_20<T> extends _i1.SmartFake
    implements _i7.ValidatedStreamWithStatus<T> {
  _FakeValidatedStreamWithStatus_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReservation_21 extends _i1.SmartFake implements _i9.Reservation {
  _FakeReservation_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEscrows_22 extends _i1.SmartFake implements _i8.Escrows {
  _FakeEscrows_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEscrowTrusts_23 extends _i1.SmartFake implements _i8.EscrowTrusts {
  _FakeEscrowTrusts_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEvm_24 extends _i1.SmartFake implements _i8.Evm {
  _FakeEvm_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEscrowFundOperation_25 extends _i1.SmartFake
    implements _i8.EscrowFundOperation {
  _FakeEscrowFundOperation_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEscrowClaimOperation_26 extends _i1.SmartFake
    implements _i8.EscrowClaimOperation {
  _FakeEscrowClaimOperation_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEscrowMethods_27 extends _i1.SmartFake implements _i8.EscrowMethods {
  _FakeEscrowMethods_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMutualEscrowResult_28 extends _i1.SmartFake
    implements _i8.MutualEscrowResult {
  _FakeMutualEscrowResult_28(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEscrowService_29 extends _i1.SmartFake implements _i9.EscrowService {
  _FakeEscrowService_29(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEscrowTrust_30 extends _i1.SmartFake implements _i9.EscrowTrust {
  _FakeEscrowTrust_30(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEscrowMethod_31 extends _i1.SmartFake implements _i9.EscrowMethod {
  _FakeEscrowMethod_31(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBadgeDefinition_32 extends _i1.SmartFake
    implements _i9.BadgeDefinition {
  _FakeBadgeDefinition_32(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBadgeAward_33 extends _i1.SmartFake implements _i9.BadgeAward {
  _FakeBadgeAward_33(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeThreads_34 extends _i1.SmartFake implements _i8.Threads {
  _FakeThreads_34(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNip01Event_35 extends _i1.SmartFake implements _i2.Nip01Event {
  _FakeNip01Event_35(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessage_36<T extends _i9.Event<_i9.EventTags>> extends _i1.SmartFake
    implements _i9.Message<T> {
  _FakeMessage_36(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReservationRequest_37 extends _i1.SmartFake
    implements _i9.ReservationRequest {
  _FakeReservationRequest_37(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeZaps_38 extends _i1.SmartFake implements _i8.Zaps {
  _FakeZaps_38(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEscrowUseCase_39 extends _i1.SmartFake implements _i8.EscrowUseCase {
  _FakeEscrowUseCase_39(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePayOperation_40<
  T extends _i10.PayParameters,
  RD extends _i10.ResolvedDetails,
  CD extends _i10.CallbackDetails,
  CmpD extends _i10.CompletedDetails
>
    extends _i1.SmartFake
    implements _i11.PayOperation<T, RD, CD, CmpD> {
  _FakePayOperation_40(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRootstock_41 extends _i1.SmartFake implements _i8.Rootstock {
  _FakeRootstock_41(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBitcoinAmount_42 extends _i1.SmartFake implements _i7.BitcoinAmount {
  _FakeBitcoinAmount_42(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEvmChain_43 extends _i1.SmartFake implements _i8.EvmChain {
  _FakeEvmChain_43(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRelayStorage_44 extends _i1.SmartFake implements _i3.RelayStorage {
  _FakeRelayStorage_44(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Auth].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuth extends _i1.Mock implements _i8.Auth {
  MockAuth() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Ndk get ndk =>
      (super.noSuchMethod(
            Invocation.getter(#ndk),
            returnValue: _FakeNdk_0(this, Invocation.getter(#ndk)),
          )
          as _i2.Ndk);

  @override
  _i3.AuthStorage get authStorage =>
      (super.noSuchMethod(
            Invocation.getter(#authStorage),
            returnValue: _FakeAuthStorage_1(
              this,
              Invocation.getter(#authStorage),
            ),
          )
          as _i3.AuthStorage);

  @override
  _i4.ValueStream<_i8.AuthState> get authState =>
      (super.noSuchMethod(
            Invocation.getter(#authState),
            returnValue: _FakeValueStream_2<_i8.AuthState>(
              this,
              Invocation.getter(#authState),
            ),
          )
          as _i4.ValueStream<_i8.AuthState>);

  @override
  set activeKeyPair(_i5.KeyPair? value) => super.noSuchMethod(
    Invocation.setter(#activeKeyPair, value),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> signup() =>
      (super.noSuchMethod(
            Invocation.method(#signup, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> signin(String? input) =>
      (super.noSuchMethod(
            Invocation.method(#signin, [input]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  bool ensureNdkAccountsMatch() =>
      (super.noSuchMethod(
            Invocation.method(#ensureNdkAccountsMatch, []),
            returnValue: false,
          )
          as bool);

  @override
  _i5.KeyPair getActiveKey() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveKey, []),
            returnValue: _FakeKeyPair_3(
              this,
              Invocation.method(#getActiveKey, []),
            ),
          )
          as _i5.KeyPair);

  @override
  _i6.EthPrivateKey getActiveEvmKey() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveEvmKey, []),
            returnValue: _FakeEthPrivateKey_4(
              this,
              Invocation.method(#getActiveEvmKey, []),
            ),
          )
          as _i6.EthPrivateKey);

  @override
  _i12.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);
}

/// A class which mocks [Requests].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequests extends _i1.Mock implements _i8.Requests {
  MockRequests() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Ndk get ndk =>
      (super.noSuchMethod(
            Invocation.getter(#ndk),
            returnValue: _FakeNdk_0(this, Invocation.getter(#ndk)),
          )
          as _i2.Ndk);

  @override
  bool get useCache =>
      (super.noSuchMethod(Invocation.getter(#useCache), returnValue: false)
          as bool);

  @override
  _i7.StreamWithStatus<T> subscribe<T extends _i2.Nip01Event>({
    required _i2.Filter? filter,
    List<String>? relays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [], {
              #filter: filter,
              #relays: relays,
            }),
            returnValue: _FakeStreamWithStatus_5<T>(
              this,
              Invocation.method(#subscribe, [], {
                #filter: filter,
                #relays: relays,
              }),
            ),
          )
          as _i7.StreamWithStatus<T>);

  @override
  _i12.Stream<T> query<T extends _i2.Nip01Event>({
    required _i2.Filter? filter,
    List<String>? relays,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#query, [], {
              #filter: filter,
              #relays: relays,
              #timeout: timeout,
            }),
            returnValue: _i12.Stream<T>.empty(),
          )
          as _i12.Stream<T>);

  @override
  _i12.Future<int> count({
    required _i2.Filter? filter,
    Duration? timeout,
    List<String>? relays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#count, [], {
              #filter: filter,
              #timeout: timeout,
              #relays: relays,
            }),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> broadcast({
    required _i2.Nip01Event? event,
    List<String>? relays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#broadcast, [], {#event: event, #relays: relays}),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<void> mock() =>
      (super.noSuchMethod(
            Invocation.method(#mock, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);
}

/// A class which mocks [MetadataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockMetadataUseCase extends _i1.Mock implements _i8.MetadataUseCase {
  MockMetadataUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Auth get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeAuth_6(this, Invocation.getter(#auth)),
          )
          as _i8.Auth);

  @override
  set auth(_i8.Auth? value) => super.noSuchMethod(
    Invocation.setter(#auth, value),
    returnValueForMissingStub: null,
  );

  @override
  _i7.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_7(this, Invocation.getter(#logger)),
          )
          as _i7.CustomLogger);

  @override
  _i8.Requests get requests =>
      (super.noSuchMethod(
            Invocation.getter(#requests),
            returnValue: _FakeRequests_8(this, Invocation.getter(#requests)),
          )
          as _i8.Requests);

  @override
  int get kind =>
      (super.noSuchMethod(Invocation.getter(#kind), returnValue: 0) as int);

  @override
  _i12.Future<_i9.ProfileMetadata?> loadMetadata(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#loadMetadata, [pubkey]),
            returnValue: _i12.Future<_i9.ProfileMetadata?>.value(),
          )
          as _i12.Future<_i9.ProfileMetadata?>);

  @override
  _i12.Future<_i12.Future<List<_i13.RelayBroadcastResponse>>>
  upsertMetadata() =>
      (super.noSuchMethod(
            Invocation.method(#upsertMetadata, []),
            returnValue:
                _i12.Future<
                  _i12.Future<List<_i13.RelayBroadcastResponse>>
                >.value(
                  _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
                    <_i13.RelayBroadcastResponse>[],
                  ),
                ),
          )
          as _i12.Future<_i12.Future<List<_i13.RelayBroadcastResponse>>>);

  @override
  _i7.StreamWithStatus<_i9.ProfileMetadata> subscribe(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [f]),
            returnValue: _FakeStreamWithStatus_5<_i9.ProfileMetadata>(
              this,
              Invocation.method(#subscribe, [f]),
            ),
          )
          as _i7.StreamWithStatus<_i9.ProfileMetadata>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> create(
    _i9.ProfileMetadata? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> update(
    _i9.ProfileMetadata? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> delete(
    _i9.ProfileMetadata? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i9.ProfileMetadata>> list(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#list, [f]),
            returnValue: _i12.Future<List<_i9.ProfileMetadata>>.value(
              <_i9.ProfileMetadata>[],
            ),
          )
          as _i12.Future<List<_i9.ProfileMetadata>>);

  @override
  _i12.Future<_i9.ProfileMetadata?> getOne(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#getOne, [f]),
            returnValue: _i12.Future<_i9.ProfileMetadata?>.value(),
          )
          as _i12.Future<_i9.ProfileMetadata?>);

  @override
  _i12.Future<_i9.ProfileMetadata?> getOneByAnchor(String? anchor) =>
      (super.noSuchMethod(
            Invocation.method(#getOneByAnchor, [anchor]),
            returnValue: _i12.Future<_i9.ProfileMetadata?>.value(),
          )
          as _i12.Future<_i9.ProfileMetadata?>);

  @override
  _i12.Future<_i9.ProfileMetadata> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i12.Future<_i9.ProfileMetadata>.value(
              _FakeProfileMetadata_9(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i12.Future<_i9.ProfileMetadata>);

  @override
  _i12.Future<int> count() =>
      (super.noSuchMethod(
            Invocation.method(#count, []),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);
}

/// A class which mocks [Nwc].
///
/// See the documentation for Mockito's code generation for more information.
class MockNwc extends _i1.Mock implements _i8.Nwc {
  MockNwc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_7(this, Invocation.getter(#logger)),
          )
          as _i7.CustomLogger);

  @override
  _i3.NwcStorage get nwcStorage =>
      (super.noSuchMethod(
            Invocation.getter(#nwcStorage),
            returnValue: _FakeNwcStorage_10(
              this,
              Invocation.getter(#nwcStorage),
            ),
          )
          as _i3.NwcStorage);

  @override
  _i2.Ndk get ndk =>
      (super.noSuchMethod(
            Invocation.getter(#ndk),
            returnValue: _FakeNdk_0(this, Invocation.getter(#ndk)),
          )
          as _i2.Ndk);

  @override
  List<_i14.NwcCubit> get connections =>
      (super.noSuchMethod(
            Invocation.getter(#connections),
            returnValue: <_i14.NwcCubit>[],
          )
          as List<_i14.NwcCubit>);

  @override
  _i12.Stream<List<_i14.NwcCubit>> get connectionsStream =>
      (super.noSuchMethod(
            Invocation.getter(#connectionsStream),
            returnValue: _i12.Stream<List<_i14.NwcCubit>>.empty(),
          )
          as _i12.Stream<List<_i14.NwcCubit>>);

  @override
  set nwcStorage(_i3.NwcStorage? value) => super.noSuchMethod(
    Invocation.setter(#nwcStorage, value),
    returnValueForMissingStub: null,
  );

  @override
  set ndk(_i2.Ndk? value) => super.noSuchMethod(
    Invocation.setter(#ndk, value),
    returnValueForMissingStub: null,
  );

  @override
  set connections(List<_i14.NwcCubit>? value) => super.noSuchMethod(
    Invocation.setter(#connections, value),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> save() =>
      (super.noSuchMethod(
            Invocation.method(#save, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> add(_i14.NwcCubit? reactiveConnection) =>
      (super.noSuchMethod(
            Invocation.method(#add, [reactiveConnection]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> remove(_i14.NwcCubit? reactiveConnection) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [reactiveConnection]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i2.NwcConnection> connect(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [url]),
            returnValue: _i12.Future<_i2.NwcConnection>.value(
              _FakeNwcConnection_11(this, Invocation.method(#connect, [url])),
            ),
          )
          as _i12.Future<_i2.NwcConnection>);

  @override
  _i12.Future<_i2.GetInfoResponse> getInfo(_i2.NwcConnection? connection) =>
      (super.noSuchMethod(
            Invocation.method(#getInfo, [connection]),
            returnValue: _i12.Future<_i2.GetInfoResponse>.value(
              _FakeGetInfoResponse_12(
                this,
                Invocation.method(#getInfo, [connection]),
              ),
            ),
          )
          as _i12.Future<_i2.GetInfoResponse>);

  @override
  _i12.Future<_i2.PayInvoiceResponse> payInvoice(
    _i2.NwcConnection? connection,
    String? invoice,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#payInvoice, [connection, invoice]),
            returnValue: _i12.Future<_i2.PayInvoiceResponse>.value(
              _FakePayInvoiceResponse_13(
                this,
                Invocation.method(#payInvoice, [connection, invoice]),
              ),
            ),
          )
          as _i12.Future<_i2.PayInvoiceResponse>);

  @override
  _i12.Future<_i2.MakeInvoiceResponse> makeInvoice(
    _i2.NwcConnection? connection, {
    required int? amountSats,
    String? description,
    String? descriptionHash,
    int? expiry,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #makeInvoice,
              [connection],
              {
                #amountSats: amountSats,
                #description: description,
                #descriptionHash: descriptionHash,
                #expiry: expiry,
              },
            ),
            returnValue: _i12.Future<_i2.MakeInvoiceResponse>.value(
              _FakeMakeInvoiceResponse_14(
                this,
                Invocation.method(
                  #makeInvoice,
                  [connection],
                  {
                    #amountSats: amountSats,
                    #description: description,
                    #descriptionHash: descriptionHash,
                    #expiry: expiry,
                  },
                ),
              ),
            ),
          )
          as _i12.Future<_i2.MakeInvoiceResponse>);

  @override
  _i12.Future<_i2.LookupInvoiceResponse> lookupInvoice(
    _i2.NwcConnection? connection, {
    String? paymentHash,
    String? invoice,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #lookupInvoice,
              [connection],
              {#paymentHash: paymentHash, #invoice: invoice},
            ),
            returnValue: _i12.Future<_i2.LookupInvoiceResponse>.value(
              _FakeLookupInvoiceResponse_15(
                this,
                Invocation.method(
                  #lookupInvoice,
                  [connection],
                  {#paymentHash: paymentHash, #invoice: invoice},
                ),
              ),
            ),
          )
          as _i12.Future<_i2.LookupInvoiceResponse>);

  @override
  _i12.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void start() => super.noSuchMethod(
    Invocation.method(#start, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [Zaps].
///
/// See the documentation for Mockito's code generation for more information.
class MockZaps extends _i1.Mock implements _i8.Zaps {
  MockZaps() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Nwc get nwc =>
      (super.noSuchMethod(
            Invocation.getter(#nwc),
            returnValue: _FakeNwc_16(this, Invocation.getter(#nwc)),
          )
          as _i8.Nwc);

  @override
  _i2.Ndk get ndk =>
      (super.noSuchMethod(
            Invocation.getter(#ndk),
            returnValue: _FakeNdk_0(this, Invocation.getter(#ndk)),
          )
          as _i2.Ndk);

  @override
  set nwc(_i8.Nwc? value) => super.noSuchMethod(
    Invocation.setter(#nwc, value),
    returnValueForMissingStub: null,
  );

  @override
  set ndk(_i2.Ndk? value) => super.noSuchMethod(
    Invocation.setter(#ndk, value),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<_i2.ZapResponse> zap({
    required String? lnurl,
    required int? amountSats,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#zap, [], {
              #lnurl: lnurl,
              #amountSats: amountSats,
            }),
            returnValue: _i12.Future<_i2.ZapResponse>.value(
              _FakeZapResponse_17(
                this,
                Invocation.method(#zap, [], {
                  #lnurl: lnurl,
                  #amountSats: amountSats,
                }),
              ),
            ),
          )
          as _i12.Future<_i2.ZapResponse>);

  @override
  _i12.Future<_i2.InvoiceResponse?> fetchInvoice({
    required String? lud16Link,
    required int? amountSats,
    _i2.ZapRequest? zapRequest,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchInvoice, [], {
              #lud16Link: lud16Link,
              #amountSats: amountSats,
              #zapRequest: zapRequest,
            }),
            returnValue: _i12.Future<_i2.InvoiceResponse?>.value(),
          )
          as _i12.Future<_i2.InvoiceResponse?>);

  @override
  _i7.StreamWithStatus<_i2.Nip01Event> subscribeZapReceipts({
    required String? pubkey,
    String? eventId,
    String? addressableId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeZapReceipts, [], {
              #pubkey: pubkey,
              #eventId: eventId,
              #addressableId: addressableId,
            }),
            returnValue: _FakeStreamWithStatus_5<_i2.Nip01Event>(
              this,
              Invocation.method(#subscribeZapReceipts, [], {
                #pubkey: pubkey,
                #eventId: eventId,
                #addressableId: addressableId,
              }),
            ),
          )
          as _i7.StreamWithStatus<_i2.Nip01Event>);
}

/// A class which mocks [Listings].
///
/// See the documentation for Mockito's code generation for more information.
class MockListings extends _i1.Mock implements _i8.Listings {
  MockListings() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_7(this, Invocation.getter(#logger)),
          )
          as _i7.CustomLogger);

  @override
  _i8.Requests get requests =>
      (super.noSuchMethod(
            Invocation.getter(#requests),
            returnValue: _FakeRequests_8(this, Invocation.getter(#requests)),
          )
          as _i8.Requests);

  @override
  int get kind =>
      (super.noSuchMethod(Invocation.getter(#kind), returnValue: 0) as int);

  @override
  _i7.StreamWithStatus<_i9.Listing> subscribe(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [f]),
            returnValue: _FakeStreamWithStatus_5<_i9.Listing>(
              this,
              Invocation.method(#subscribe, [f]),
            ),
          )
          as _i7.StreamWithStatus<_i9.Listing>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> create(_i9.Listing? event) =>
      (super.noSuchMethod(
            Invocation.method(#create, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> update(_i9.Listing? event) =>
      (super.noSuchMethod(
            Invocation.method(#update, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> delete(_i9.Listing? event) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i9.Listing>> list(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#list, [f]),
            returnValue: _i12.Future<List<_i9.Listing>>.value(<_i9.Listing>[]),
          )
          as _i12.Future<List<_i9.Listing>>);

  @override
  _i12.Future<_i9.Listing?> getOne(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#getOne, [f]),
            returnValue: _i12.Future<_i9.Listing?>.value(),
          )
          as _i12.Future<_i9.Listing?>);

  @override
  _i12.Future<_i9.Listing?> getOneByAnchor(String? anchor) =>
      (super.noSuchMethod(
            Invocation.method(#getOneByAnchor, [anchor]),
            returnValue: _i12.Future<_i9.Listing?>.value(),
          )
          as _i12.Future<_i9.Listing?>);

  @override
  _i12.Future<_i9.Listing> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i12.Future<_i9.Listing>.value(
              _FakeListing_18(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i12.Future<_i9.Listing>);

  @override
  _i12.Future<int> count() =>
      (super.noSuchMethod(
            Invocation.method(#count, []),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);
}

/// A class which mocks [Reservations].
///
/// See the documentation for Mockito's code generation for more information.
class MockReservations extends _i1.Mock implements _i8.Reservations {
  MockReservations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Messaging get messaging =>
      (super.noSuchMethod(
            Invocation.getter(#messaging),
            returnValue: _FakeMessaging_19(this, Invocation.getter(#messaging)),
          )
          as _i8.Messaging);

  @override
  _i8.Auth get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeAuth_6(this, Invocation.getter(#auth)),
          )
          as _i8.Auth);

  @override
  _i7.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_7(this, Invocation.getter(#logger)),
          )
          as _i7.CustomLogger);

  @override
  _i8.Requests get requests =>
      (super.noSuchMethod(
            Invocation.getter(#requests),
            returnValue: _FakeRequests_8(this, Invocation.getter(#requests)),
          )
          as _i8.Requests);

  @override
  int get kind =>
      (super.noSuchMethod(Invocation.getter(#kind), returnValue: 0) as int);

  @override
  _i12.Future<List<_i9.Reservation>> getListingReservations({
    required String? listingAnchor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getListingReservations, [], {
              #listingAnchor: listingAnchor,
            }),
            returnValue: _i12.Future<List<_i9.Reservation>>.value(
              <_i9.Reservation>[],
            ),
          )
          as _i12.Future<List<_i9.Reservation>>);

  @override
  dynamic groupByCommitment(
    List<_i9.Reservation>? reservations,
    _i9.Listing? listing,
  ) => super.noSuchMethod(
    Invocation.method(#groupByCommitment, [reservations, listing]),
  );

  @override
  _i7.ValidatedStreamWithStatus<_i9.Reservation> subscribeValidatedForListing({
    required _i9.Listing? listing,
    Duration? debounce = const Duration(milliseconds: 350),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeValidatedForListing, [], {
              #listing: listing,
              #debounce: debounce,
            }),
            returnValue: _FakeValidatedStreamWithStatus_20<_i9.Reservation>(
              this,
              Invocation.method(#subscribeValidatedForListing, [], {
                #listing: listing,
                #debounce: debounce,
              }),
            ),
          )
          as _i7.ValidatedStreamWithStatus<_i9.Reservation>);

  @override
  _i7.ValidatedStreamWithStatus<_i9.Reservation>
  subscribeUncancelledReservations({
    required _i9.Listing? listing,
    Duration? debounce = const Duration(milliseconds: 350),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeUncancelledReservations, [], {
              #listing: listing,
              #debounce: debounce,
            }),
            returnValue: _FakeValidatedStreamWithStatus_20<_i9.Reservation>(
              this,
              Invocation.method(#subscribeUncancelledReservations, [], {
                #listing: listing,
                #debounce: debounce,
              }),
            ),
          )
          as _i7.ValidatedStreamWithStatus<_i9.Reservation>);

  @override
  Map<
    String,
    ({_i9.Reservation? buyerReservation, _i9.Reservation? sellerReservation})
  >
  groupByThread(List<_i9.Reservation>? reservations) =>
      (super.noSuchMethod(
            Invocation.method(#groupByThread, [reservations]),
            returnValue:
                <
                  String,
                  ({
                    _i9.Reservation? buyerReservation,
                    _i9.Reservation? sellerReservation,
                  })
                >{},
          )
          as Map<
            String,
            ({
              _i9.Reservation? buyerReservation,
              _i9.Reservation? sellerReservation,
            })
          >);

  @override
  _i7.StreamWithStatus<_i9.Reservation> subscribeToMyReservations() =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToMyReservations, []),
            returnValue: _FakeStreamWithStatus_5<_i9.Reservation>(
              this,
              Invocation.method(#subscribeToMyReservations, []),
            ),
          )
          as _i7.StreamWithStatus<_i9.Reservation>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> accept(
    String? anchor,
    _i9.ReservationRequest? request,
    String? guestPubkey,
    String? saltedPubkey,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#accept, [
              anchor,
              request,
              guestPubkey,
              saltedPubkey,
            ]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<_i9.Reservation> createSelfSigned({
    required _i5.KeyPair? activeKeyPair,
    required _i9.ReservationRequest? reservationRequest,
    required _i9.PaymentProof? proof,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSelfSigned, [], {
              #activeKeyPair: activeKeyPair,
              #reservationRequest: reservationRequest,
              #proof: proof,
            }),
            returnValue: _i12.Future<_i9.Reservation>.value(
              _FakeReservation_21(
                this,
                Invocation.method(#createSelfSigned, [], {
                  #activeKeyPair: activeKeyPair,
                  #reservationRequest: reservationRequest,
                  #proof: proof,
                }),
              ),
            ),
          )
          as _i12.Future<_i9.Reservation>);

  @override
  _i12.Future<_i9.Reservation> cancel(_i9.Reservation? reservation) =>
      (super.noSuchMethod(
            Invocation.method(#cancel, [reservation]),
            returnValue: _i12.Future<_i9.Reservation>.value(
              _FakeReservation_21(
                this,
                Invocation.method(#cancel, [reservation]),
              ),
            ),
          )
          as _i12.Future<_i9.Reservation>);

  @override
  _i12.Future<_i9.Reservation> createBlocked({
    required String? listingAnchor,
    required DateTime? start,
    required DateTime? end,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createBlocked, [], {
              #listingAnchor: listingAnchor,
              #start: start,
              #end: end,
            }),
            returnValue: _i12.Future<_i9.Reservation>.value(
              _FakeReservation_21(
                this,
                Invocation.method(#createBlocked, [], {
                  #listingAnchor: listingAnchor,
                  #start: start,
                  #end: end,
                }),
              ),
            ),
          )
          as _i12.Future<_i9.Reservation>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.StreamWithStatus<_i9.Reservation> subscribe(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [f]),
            returnValue: _FakeStreamWithStatus_5<_i9.Reservation>(
              this,
              Invocation.method(#subscribe, [f]),
            ),
          )
          as _i7.StreamWithStatus<_i9.Reservation>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> create(
    _i9.Reservation? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> update(
    _i9.Reservation? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> delete(
    _i9.Reservation? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i9.Reservation>> list(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#list, [f]),
            returnValue: _i12.Future<List<_i9.Reservation>>.value(
              <_i9.Reservation>[],
            ),
          )
          as _i12.Future<List<_i9.Reservation>>);

  @override
  _i12.Future<_i9.Reservation?> getOne(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#getOne, [f]),
            returnValue: _i12.Future<_i9.Reservation?>.value(),
          )
          as _i12.Future<_i9.Reservation?>);

  @override
  _i12.Future<_i9.Reservation?> getOneByAnchor(String? anchor) =>
      (super.noSuchMethod(
            Invocation.method(#getOneByAnchor, [anchor]),
            returnValue: _i12.Future<_i9.Reservation?>.value(),
          )
          as _i12.Future<_i9.Reservation?>);

  @override
  _i12.Future<_i9.Reservation> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i12.Future<_i9.Reservation>.value(
              _FakeReservation_21(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i12.Future<_i9.Reservation>);

  @override
  _i12.Future<int> count() =>
      (super.noSuchMethod(
            Invocation.method(#count, []),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);
}

/// A class which mocks [EscrowUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEscrowUseCase extends _i1.Mock implements _i8.EscrowUseCase {
  MockEscrowUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_7(this, Invocation.getter(#logger)),
          )
          as _i7.CustomLogger);

  @override
  _i8.Auth get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeAuth_6(this, Invocation.getter(#auth)),
          )
          as _i8.Auth);

  @override
  _i8.Escrows get escrows =>
      (super.noSuchMethod(
            Invocation.getter(#escrows),
            returnValue: _FakeEscrows_22(this, Invocation.getter(#escrows)),
          )
          as _i8.Escrows);

  @override
  _i8.EscrowTrusts get escrowTrusts =>
      (super.noSuchMethod(
            Invocation.getter(#escrowTrusts),
            returnValue: _FakeEscrowTrusts_23(
              this,
              Invocation.getter(#escrowTrusts),
            ),
          )
          as _i8.EscrowTrusts);

  @override
  _i8.Evm get evm =>
      (super.noSuchMethod(
            Invocation.getter(#evm),
            returnValue: _FakeEvm_24(this, Invocation.getter(#evm)),
          )
          as _i8.Evm);

  @override
  _i8.EscrowFundOperation fund(_i8.EscrowFundParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#fund, [params]),
            returnValue: _FakeEscrowFundOperation_25(
              this,
              Invocation.method(#fund, [params]),
            ),
          )
          as _i8.EscrowFundOperation);

  @override
  _i8.EscrowClaimOperation claim(_i8.EscrowClaimParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#claim, [params]),
            returnValue: _FakeEscrowClaimOperation_26(
              this,
              Invocation.method(#claim, [params]),
            ),
          )
          as _i8.EscrowClaimOperation);

  @override
  _i7.StreamWithStatus<_i15.EscrowEvent> checkEscrowStatus(
    _i9.EscrowServiceSelected? selectedEscrow,
    String? tradeId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkEscrowStatus, [selectedEscrow, tradeId]),
            returnValue: _FakeStreamWithStatus_5<_i15.EscrowEvent>(
              this,
              Invocation.method(#checkEscrowStatus, [selectedEscrow, tradeId]),
            ),
          )
          as _i7.StreamWithStatus<_i15.EscrowEvent>);
}

/// A class which mocks [Escrows].
///
/// See the documentation for Mockito's code generation for more information.
class MockEscrows extends _i1.Mock implements _i8.Escrows {
  MockEscrows() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.EscrowMethods get escrowMethods =>
      (super.noSuchMethod(
            Invocation.getter(#escrowMethods),
            returnValue: _FakeEscrowMethods_27(
              this,
              Invocation.getter(#escrowMethods),
            ),
          )
          as _i8.EscrowMethods);

  @override
  _i8.EscrowTrusts get escrowTrusts =>
      (super.noSuchMethod(
            Invocation.getter(#escrowTrusts),
            returnValue: _FakeEscrowTrusts_23(
              this,
              Invocation.getter(#escrowTrusts),
            ),
          )
          as _i8.EscrowTrusts);

  @override
  set escrowMethods(_i8.EscrowMethods? value) => super.noSuchMethod(
    Invocation.setter(#escrowMethods, value),
    returnValueForMissingStub: null,
  );

  @override
  set escrowTrusts(_i8.EscrowTrusts? value) => super.noSuchMethod(
    Invocation.setter(#escrowTrusts, value),
    returnValueForMissingStub: null,
  );

  @override
  _i7.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_7(this, Invocation.getter(#logger)),
          )
          as _i7.CustomLogger);

  @override
  _i8.Requests get requests =>
      (super.noSuchMethod(
            Invocation.getter(#requests),
            returnValue: _FakeRequests_8(this, Invocation.getter(#requests)),
          )
          as _i8.Requests);

  @override
  int get kind =>
      (super.noSuchMethod(Invocation.getter(#kind), returnValue: 0) as int);

  @override
  _i12.Future<_i8.MutualEscrowResult> determineMutualEscrow(
    String? pubkey1,
    String? pubkey2,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#determineMutualEscrow, [pubkey1, pubkey2]),
            returnValue: _i12.Future<_i8.MutualEscrowResult>.value(
              _FakeMutualEscrowResult_28(
                this,
                Invocation.method(#determineMutualEscrow, [pubkey1, pubkey2]),
              ),
            ),
          )
          as _i12.Future<_i8.MutualEscrowResult>);

  @override
  _i7.StreamWithStatus<_i9.EscrowService> subscribe(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [f]),
            returnValue: _FakeStreamWithStatus_5<_i9.EscrowService>(
              this,
              Invocation.method(#subscribe, [f]),
            ),
          )
          as _i7.StreamWithStatus<_i9.EscrowService>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> create(
    _i9.EscrowService? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> update(
    _i9.EscrowService? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> delete(
    _i9.EscrowService? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i9.EscrowService>> list(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#list, [f]),
            returnValue: _i12.Future<List<_i9.EscrowService>>.value(
              <_i9.EscrowService>[],
            ),
          )
          as _i12.Future<List<_i9.EscrowService>>);

  @override
  _i12.Future<_i9.EscrowService?> getOne(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#getOne, [f]),
            returnValue: _i12.Future<_i9.EscrowService?>.value(),
          )
          as _i12.Future<_i9.EscrowService?>);

  @override
  _i12.Future<_i9.EscrowService?> getOneByAnchor(String? anchor) =>
      (super.noSuchMethod(
            Invocation.method(#getOneByAnchor, [anchor]),
            returnValue: _i12.Future<_i9.EscrowService?>.value(),
          )
          as _i12.Future<_i9.EscrowService?>);

  @override
  _i12.Future<_i9.EscrowService> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i12.Future<_i9.EscrowService>.value(
              _FakeEscrowService_29(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i12.Future<_i9.EscrowService>);

  @override
  _i12.Future<int> count() =>
      (super.noSuchMethod(
            Invocation.method(#count, []),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);
}

/// A class which mocks [EscrowTrusts].
///
/// See the documentation for Mockito's code generation for more information.
class MockEscrowTrusts extends _i1.Mock implements _i8.EscrowTrusts {
  MockEscrowTrusts() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Auth get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeAuth_6(this, Invocation.getter(#auth)),
          )
          as _i8.Auth);

  @override
  _i7.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_7(this, Invocation.getter(#logger)),
          )
          as _i7.CustomLogger);

  @override
  _i8.Requests get requests =>
      (super.noSuchMethod(
            Invocation.getter(#requests),
            returnValue: _FakeRequests_8(this, Invocation.getter(#requests)),
          )
          as _i8.Requests);

  @override
  int get kind =>
      (super.noSuchMethod(Invocation.getter(#kind), returnValue: 0) as int);

  @override
  _i12.Future<_i9.EscrowTrust?> trusted(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#trusted, [pubkey]),
            returnValue: _i12.Future<_i9.EscrowTrust?>.value(),
          )
          as _i12.Future<_i9.EscrowTrust?>);

  @override
  _i12.Future<_i9.EscrowTrust?> myTrusted() =>
      (super.noSuchMethod(
            Invocation.method(#myTrusted, []),
            returnValue: _i12.Future<_i9.EscrowTrust?>.value(),
          )
          as _i12.Future<_i9.EscrowTrust?>);

  @override
  _i7.StreamWithStatus<_i9.EscrowTrust> subscribe(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [f]),
            returnValue: _FakeStreamWithStatus_5<_i9.EscrowTrust>(
              this,
              Invocation.method(#subscribe, [f]),
            ),
          )
          as _i7.StreamWithStatus<_i9.EscrowTrust>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> create(
    _i9.EscrowTrust? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> update(
    _i9.EscrowTrust? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> delete(
    _i9.EscrowTrust? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i9.EscrowTrust>> list(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#list, [f]),
            returnValue: _i12.Future<List<_i9.EscrowTrust>>.value(
              <_i9.EscrowTrust>[],
            ),
          )
          as _i12.Future<List<_i9.EscrowTrust>>);

  @override
  _i12.Future<_i9.EscrowTrust?> getOne(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#getOne, [f]),
            returnValue: _i12.Future<_i9.EscrowTrust?>.value(),
          )
          as _i12.Future<_i9.EscrowTrust?>);

  @override
  _i12.Future<_i9.EscrowTrust?> getOneByAnchor(String? anchor) =>
      (super.noSuchMethod(
            Invocation.method(#getOneByAnchor, [anchor]),
            returnValue: _i12.Future<_i9.EscrowTrust?>.value(),
          )
          as _i12.Future<_i9.EscrowTrust?>);

  @override
  _i12.Future<_i9.EscrowTrust> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i12.Future<_i9.EscrowTrust>.value(
              _FakeEscrowTrust_30(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i12.Future<_i9.EscrowTrust>);

  @override
  _i12.Future<int> count() =>
      (super.noSuchMethod(
            Invocation.method(#count, []),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);
}

/// A class which mocks [EscrowMethods].
///
/// See the documentation for Mockito's code generation for more information.
class MockEscrowMethods extends _i1.Mock implements _i8.EscrowMethods {
  MockEscrowMethods() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_7(this, Invocation.getter(#logger)),
          )
          as _i7.CustomLogger);

  @override
  _i8.Requests get requests =>
      (super.noSuchMethod(
            Invocation.getter(#requests),
            returnValue: _FakeRequests_8(this, Invocation.getter(#requests)),
          )
          as _i8.Requests);

  @override
  int get kind =>
      (super.noSuchMethod(Invocation.getter(#kind), returnValue: 0) as int);

  @override
  _i7.StreamWithStatus<_i9.EscrowMethod> subscribe(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [f]),
            returnValue: _FakeStreamWithStatus_5<_i9.EscrowMethod>(
              this,
              Invocation.method(#subscribe, [f]),
            ),
          )
          as _i7.StreamWithStatus<_i9.EscrowMethod>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> create(
    _i9.EscrowMethod? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> update(
    _i9.EscrowMethod? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> delete(
    _i9.EscrowMethod? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i9.EscrowMethod>> list(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#list, [f]),
            returnValue: _i12.Future<List<_i9.EscrowMethod>>.value(
              <_i9.EscrowMethod>[],
            ),
          )
          as _i12.Future<List<_i9.EscrowMethod>>);

  @override
  _i12.Future<_i9.EscrowMethod?> getOne(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#getOne, [f]),
            returnValue: _i12.Future<_i9.EscrowMethod?>.value(),
          )
          as _i12.Future<_i9.EscrowMethod?>);

  @override
  _i12.Future<_i9.EscrowMethod?> getOneByAnchor(String? anchor) =>
      (super.noSuchMethod(
            Invocation.method(#getOneByAnchor, [anchor]),
            returnValue: _i12.Future<_i9.EscrowMethod?>.value(),
          )
          as _i12.Future<_i9.EscrowMethod?>);

  @override
  _i12.Future<_i9.EscrowMethod> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i12.Future<_i9.EscrowMethod>.value(
              _FakeEscrowMethod_31(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i12.Future<_i9.EscrowMethod>);

  @override
  _i12.Future<int> count() =>
      (super.noSuchMethod(
            Invocation.method(#count, []),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);
}

/// A class which mocks [BadgeDefinitions].
///
/// See the documentation for Mockito's code generation for more information.
class MockBadgeDefinitions extends _i1.Mock implements _i8.BadgeDefinitions {
  MockBadgeDefinitions() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_7(this, Invocation.getter(#logger)),
          )
          as _i7.CustomLogger);

  @override
  _i8.Requests get requests =>
      (super.noSuchMethod(
            Invocation.getter(#requests),
            returnValue: _FakeRequests_8(this, Invocation.getter(#requests)),
          )
          as _i8.Requests);

  @override
  int get kind =>
      (super.noSuchMethod(Invocation.getter(#kind), returnValue: 0) as int);

  @override
  _i7.StreamWithStatus<_i9.BadgeDefinition> subscribe(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [f]),
            returnValue: _FakeStreamWithStatus_5<_i9.BadgeDefinition>(
              this,
              Invocation.method(#subscribe, [f]),
            ),
          )
          as _i7.StreamWithStatus<_i9.BadgeDefinition>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> create(
    _i9.BadgeDefinition? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> update(
    _i9.BadgeDefinition? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> delete(
    _i9.BadgeDefinition? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i9.BadgeDefinition>> list(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#list, [f]),
            returnValue: _i12.Future<List<_i9.BadgeDefinition>>.value(
              <_i9.BadgeDefinition>[],
            ),
          )
          as _i12.Future<List<_i9.BadgeDefinition>>);

  @override
  _i12.Future<_i9.BadgeDefinition?> getOne(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#getOne, [f]),
            returnValue: _i12.Future<_i9.BadgeDefinition?>.value(),
          )
          as _i12.Future<_i9.BadgeDefinition?>);

  @override
  _i12.Future<_i9.BadgeDefinition?> getOneByAnchor(String? anchor) =>
      (super.noSuchMethod(
            Invocation.method(#getOneByAnchor, [anchor]),
            returnValue: _i12.Future<_i9.BadgeDefinition?>.value(),
          )
          as _i12.Future<_i9.BadgeDefinition?>);

  @override
  _i12.Future<_i9.BadgeDefinition> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i12.Future<_i9.BadgeDefinition>.value(
              _FakeBadgeDefinition_32(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i12.Future<_i9.BadgeDefinition>);

  @override
  _i12.Future<int> count() =>
      (super.noSuchMethod(
            Invocation.method(#count, []),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);
}

/// A class which mocks [BadgeAwards].
///
/// See the documentation for Mockito's code generation for more information.
class MockBadgeAwards extends _i1.Mock implements _i8.BadgeAwards {
  MockBadgeAwards() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_7(this, Invocation.getter(#logger)),
          )
          as _i7.CustomLogger);

  @override
  _i8.Requests get requests =>
      (super.noSuchMethod(
            Invocation.getter(#requests),
            returnValue: _FakeRequests_8(this, Invocation.getter(#requests)),
          )
          as _i8.Requests);

  @override
  int get kind =>
      (super.noSuchMethod(Invocation.getter(#kind), returnValue: 0) as int);

  @override
  _i7.StreamWithStatus<_i9.BadgeAward> subscribe(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [f]),
            returnValue: _FakeStreamWithStatus_5<_i9.BadgeAward>(
              this,
              Invocation.method(#subscribe, [f]),
            ),
          )
          as _i7.StreamWithStatus<_i9.BadgeAward>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> create(
    _i9.BadgeAward? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> update(
    _i9.BadgeAward? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> delete(
    _i9.BadgeAward? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i9.BadgeAward>> list(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#list, [f]),
            returnValue: _i12.Future<List<_i9.BadgeAward>>.value(
              <_i9.BadgeAward>[],
            ),
          )
          as _i12.Future<List<_i9.BadgeAward>>);

  @override
  _i12.Future<_i9.BadgeAward?> getOne(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#getOne, [f]),
            returnValue: _i12.Future<_i9.BadgeAward?>.value(),
          )
          as _i12.Future<_i9.BadgeAward?>);

  @override
  _i12.Future<_i9.BadgeAward?> getOneByAnchor(String? anchor) =>
      (super.noSuchMethod(
            Invocation.method(#getOneByAnchor, [anchor]),
            returnValue: _i12.Future<_i9.BadgeAward?>.value(),
          )
          as _i12.Future<_i9.BadgeAward?>);

  @override
  _i12.Future<_i9.BadgeAward> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i12.Future<_i9.BadgeAward>.value(
              _FakeBadgeAward_33(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i12.Future<_i9.BadgeAward>);

  @override
  _i12.Future<int> count() =>
      (super.noSuchMethod(
            Invocation.method(#count, []),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);
}

/// A class which mocks [Messaging].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessaging extends _i1.Mock implements _i8.Messaging {
  MockMessaging() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Ndk get ndk =>
      (super.noSuchMethod(
            Invocation.getter(#ndk),
            returnValue: _FakeNdk_0(this, Invocation.getter(#ndk)),
          )
          as _i2.Ndk);

  @override
  _i8.Requests get requests =>
      (super.noSuchMethod(
            Invocation.getter(#requests),
            returnValue: _FakeRequests_8(this, Invocation.getter(#requests)),
          )
          as _i8.Requests);

  @override
  _i7.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_7(this, Invocation.getter(#logger)),
          )
          as _i7.CustomLogger);

  @override
  _i8.Threads get threads =>
      (super.noSuchMethod(
            Invocation.getter(#threads),
            returnValue: _FakeThreads_34(this, Invocation.getter(#threads)),
          )
          as _i8.Threads);

  @override
  _i12.Future<_i2.Nip01Event> getRumour(
    String? content,
    List<List<String>>? tags,
    List<String>? recipientPubkeys,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRumour, [content, tags, recipientPubkeys]),
            returnValue: _i12.Future<_i2.Nip01Event>.value(
              _FakeNip01Event_35(
                this,
                Invocation.method(#getRumour, [
                  content,
                  tags,
                  recipientPubkeys,
                ]),
              ),
            ),
          )
          as _i12.Future<_i2.Nip01Event>);

  @override
  _i12.Future<_i9.Message<_i9.Event<_i9.EventTags>>> broadcastTextAndAwait({
    required String? content,
    required List<List<String>>? tags,
    required List<String>? recipientPubkeys,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastTextAndAwait, [], {
              #content: content,
              #tags: tags,
              #recipientPubkeys: recipientPubkeys,
            }),
            returnValue:
                _i12.Future<_i9.Message<_i9.Event<_i9.EventTags>>>.value(
                  _FakeMessage_36<_i9.Event<_i9.EventTags>>(
                    this,
                    Invocation.method(#broadcastTextAndAwait, [], {
                      #content: content,
                      #tags: tags,
                      #recipientPubkeys: recipientPubkeys,
                    }),
                  ),
                ),
          )
          as _i12.Future<_i9.Message<_i9.Event<_i9.EventTags>>>);

  @override
  _i12.Future<List<_i12.Future<List<_i13.RelayBroadcastResponse>>>>
  broadcastText({
    required String? content,
    required List<List<String>>? tags,
    required List<String>? recipientPubkeys,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastText, [], {
              #content: content,
              #tags: tags,
              #recipientPubkeys: recipientPubkeys,
            }),
            returnValue:
                _i12.Future<
                  List<_i12.Future<List<_i13.RelayBroadcastResponse>>>
                >.value(<_i12.Future<List<_i13.RelayBroadcastResponse>>>[]),
          )
          as _i12.Future<List<_i12.Future<List<_i13.RelayBroadcastResponse>>>>);

  @override
  _i12.Future<_i9.Message<_i9.Event<_i9.EventTags>>> broadcastEventAndWait({
    required _i2.Nip01Event? event,
    required List<List<String>>? tags,
    required List<String>? recipientPubkeys,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastEventAndWait, [], {
              #event: event,
              #tags: tags,
              #recipientPubkeys: recipientPubkeys,
            }),
            returnValue:
                _i12.Future<_i9.Message<_i9.Event<_i9.EventTags>>>.value(
                  _FakeMessage_36<_i9.Event<_i9.EventTags>>(
                    this,
                    Invocation.method(#broadcastEventAndWait, [], {
                      #event: event,
                      #tags: tags,
                      #recipientPubkeys: recipientPubkeys,
                    }),
                  ),
                ),
          )
          as _i12.Future<_i9.Message<_i9.Event<_i9.EventTags>>>);

  @override
  _i12.Future<List<_i12.Future<List<_i13.RelayBroadcastResponse>>>>
  broadcastEvent({
    required _i2.Nip01Event? event,
    required List<List<String>>? tags,
    required List<String>? recipientPubkeys,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastEvent, [], {
              #event: event,
              #tags: tags,
              #recipientPubkeys: recipientPubkeys,
            }),
            returnValue:
                _i12.Future<
                  List<_i12.Future<List<_i13.RelayBroadcastResponse>>>
                >.value(<_i12.Future<List<_i13.RelayBroadcastResponse>>>[]),
          )
          as _i12.Future<List<_i12.Future<List<_i13.RelayBroadcastResponse>>>>);
}

/// A class which mocks [ReservationRequests].
///
/// See the documentation for Mockito's code generation for more information.
class MockReservationRequests extends _i1.Mock
    implements _i8.ReservationRequests {
  MockReservationRequests() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Ndk get ndk =>
      (super.noSuchMethod(
            Invocation.getter(#ndk),
            returnValue: _FakeNdk_0(this, Invocation.getter(#ndk)),
          )
          as _i2.Ndk);

  @override
  _i8.Auth get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeAuth_6(this, Invocation.getter(#auth)),
          )
          as _i8.Auth);

  @override
  _i7.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_7(this, Invocation.getter(#logger)),
          )
          as _i7.CustomLogger);

  @override
  _i8.Requests get requests =>
      (super.noSuchMethod(
            Invocation.getter(#requests),
            returnValue: _FakeRequests_8(this, Invocation.getter(#requests)),
          )
          as _i8.Requests);

  @override
  int get kind =>
      (super.noSuchMethod(Invocation.getter(#kind), returnValue: 0) as int);

  @override
  _i12.Future<_i9.ReservationRequest> createReservationRequest({
    required _i9.Listing? listing,
    required DateTime? startDate,
    required DateTime? endDate,
    required String? recipientPubkey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createReservationRequest, [], {
              #listing: listing,
              #startDate: startDate,
              #endDate: endDate,
              #recipientPubkey: recipientPubkey,
            }),
            returnValue: _i12.Future<_i9.ReservationRequest>.value(
              _FakeReservationRequest_37(
                this,
                Invocation.method(#createReservationRequest, [], {
                  #listing: listing,
                  #startDate: startDate,
                  #endDate: endDate,
                  #recipientPubkey: recipientPubkey,
                }),
              ),
            ),
          )
          as _i12.Future<_i9.ReservationRequest>);

  @override
  _i7.StreamWithStatus<_i2.Nip01Event> subscribe(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [f]),
            returnValue: _FakeStreamWithStatus_5<_i2.Nip01Event>(
              this,
              Invocation.method(#subscribe, [f]),
            ),
          )
          as _i7.StreamWithStatus<_i2.Nip01Event>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> create(
    _i2.Nip01Event? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> update(
    _i2.Nip01Event? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> delete(
    _i2.Nip01Event? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i2.Nip01Event>> list(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#list, [f]),
            returnValue: _i12.Future<List<_i2.Nip01Event>>.value(
              <_i2.Nip01Event>[],
            ),
          )
          as _i12.Future<List<_i2.Nip01Event>>);

  @override
  _i12.Future<_i2.Nip01Event?> getOne(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#getOne, [f]),
            returnValue: _i12.Future<_i2.Nip01Event?>.value(),
          )
          as _i12.Future<_i2.Nip01Event?>);

  @override
  _i12.Future<_i2.Nip01Event?> getOneByAnchor(String? anchor) =>
      (super.noSuchMethod(
            Invocation.method(#getOneByAnchor, [anchor]),
            returnValue: _i12.Future<_i2.Nip01Event?>.value(),
          )
          as _i12.Future<_i2.Nip01Event?>);

  @override
  _i12.Future<_i2.Nip01Event> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i12.Future<_i2.Nip01Event>.value(
              _FakeNip01Event_35(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i12.Future<_i2.Nip01Event>);

  @override
  _i12.Future<int> count() =>
      (super.noSuchMethod(
            Invocation.method(#count, []),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);
}

/// A class which mocks [Payments].
///
/// See the documentation for Mockito's code generation for more information.
class MockPayments extends _i1.Mock implements _i8.Payments {
  MockPayments() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_7(this, Invocation.getter(#logger)),
          )
          as _i7.CustomLogger);

  @override
  _i8.Zaps get zaps =>
      (super.noSuchMethod(
            Invocation.getter(#zaps),
            returnValue: _FakeZaps_38(this, Invocation.getter(#zaps)),
          )
          as _i8.Zaps);

  @override
  _i8.Nwc get nwc =>
      (super.noSuchMethod(
            Invocation.getter(#nwc),
            returnValue: _FakeNwc_16(this, Invocation.getter(#nwc)),
          )
          as _i8.Nwc);

  @override
  _i8.EscrowUseCase get escrow =>
      (super.noSuchMethod(
            Invocation.getter(#escrow),
            returnValue: _FakeEscrowUseCase_39(
              this,
              Invocation.getter(#escrow),
            ),
          )
          as _i8.EscrowUseCase);

  @override
  set zaps(_i8.Zaps? value) => super.noSuchMethod(
    Invocation.setter(#zaps, value),
    returnValueForMissingStub: null,
  );

  @override
  set nwc(_i8.Nwc? value) => super.noSuchMethod(
    Invocation.setter(#nwc, value),
    returnValueForMissingStub: null,
  );

  @override
  _i11.PayOperation<
    _i10.PayParameters,
    _i10.ResolvedDetails,
    _i10.CallbackDetails,
    _i10.CompletedDetails
  >
  pay(_i10.PayParameters? params) =>
      (super.noSuchMethod(
            Invocation.method(#pay, [params]),
            returnValue:
                _FakePayOperation_40<
                  _i10.PayParameters,
                  _i10.ResolvedDetails,
                  _i10.CallbackDetails,
                  _i10.CompletedDetails
                >(this, Invocation.method(#pay, [params])),
          )
          as _i11.PayOperation<
            _i10.PayParameters,
            _i10.ResolvedDetails,
            _i10.CallbackDetails,
            _i10.CompletedDetails
          >);
}

/// A class which mocks [Evm].
///
/// See the documentation for Mockito's code generation for more information.
class MockEvm extends _i1.Mock implements _i8.Evm {
  MockEvm() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_7(this, Invocation.getter(#logger)),
          )
          as _i7.CustomLogger);

  @override
  _i8.Auth get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeAuth_6(this, Invocation.getter(#auth)),
          )
          as _i8.Auth);

  @override
  _i8.Rootstock get rootstock =>
      (super.noSuchMethod(
            Invocation.getter(#rootstock),
            returnValue: _FakeRootstock_41(this, Invocation.getter(#rootstock)),
          )
          as _i8.Rootstock);

  @override
  List<_i8.EvmChain> get supportedEvmChains =>
      (super.noSuchMethod(
            Invocation.getter(#supportedEvmChains),
            returnValue: <_i8.EvmChain>[],
          )
          as List<_i8.EvmChain>);

  @override
  set supportedEvmChains(List<_i8.EvmChain>? value) => super.noSuchMethod(
    Invocation.setter(#supportedEvmChains, value),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<_i7.BitcoinAmount> getBalance() =>
      (super.noSuchMethod(
            Invocation.method(#getBalance, []),
            returnValue: _i12.Future<_i7.BitcoinAmount>.value(
              _FakeBitcoinAmount_42(this, Invocation.method(#getBalance, [])),
            ),
          )
          as _i12.Future<_i7.BitcoinAmount>);

  @override
  _i8.EvmChain getChainForEscrowService(_i9.EscrowService? service) =>
      (super.noSuchMethod(
            Invocation.method(#getChainForEscrowService, [service]),
            returnValue: _FakeEvmChain_43(
              this,
              Invocation.method(#getChainForEscrowService, [service]),
            ),
          )
          as _i8.EvmChain);

  @override
  _i4.ValueStream<_i7.BitcoinAmount> subscribeBalance() =>
      (super.noSuchMethod(
            Invocation.method(#subscribeBalance, []),
            returnValue: _FakeValueStream_2<_i7.BitcoinAmount>(
              this,
              Invocation.method(#subscribeBalance, []),
            ),
          )
          as _i4.ValueStream<_i7.BitcoinAmount>);

  @override
  _i12.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i8.EvmChain> getClientForChainId(int? chainId) =>
      (super.noSuchMethod(
            Invocation.method(#getClientForChainId, [chainId]),
            returnValue: _i12.Future<_i8.EvmChain>.value(
              _FakeEvmChain_43(
                this,
                Invocation.method(#getClientForChainId, [chainId]),
              ),
            ),
          )
          as _i12.Future<_i8.EvmChain>);
}

/// A class which mocks [Relays].
///
/// See the documentation for Mockito's code generation for more information.
class MockRelays extends _i1.Mock implements _i8.Relays {
  MockRelays() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_7(this, Invocation.getter(#logger)),
          )
          as _i7.CustomLogger);

  @override
  _i2.Ndk get ndk =>
      (super.noSuchMethod(
            Invocation.getter(#ndk),
            returnValue: _FakeNdk_0(this, Invocation.getter(#ndk)),
          )
          as _i2.Ndk);

  @override
  _i3.RelayStorage get relayStorage =>
      (super.noSuchMethod(
            Invocation.getter(#relayStorage),
            returnValue: _FakeRelayStorage_44(
              this,
              Invocation.getter(#relayStorage),
            ),
          )
          as _i3.RelayStorage);

  @override
  _i12.Future<void> add(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#add, [url]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> remove(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [url]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> connect() =>
      (super.noSuchMethod(
            Invocation.method(#connect, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Stream<Map<String, _i13.RelayConnectivity<dynamic>>> connectivity() =>
      (super.noSuchMethod(
            Invocation.method(#connectivity, []),
            returnValue:
                _i12.Stream<
                  Map<String, _i13.RelayConnectivity<dynamic>>
                >.empty(),
          )
          as _i12.Stream<Map<String, _i13.RelayConnectivity<dynamic>>>);
}
