// Mocks generated by Mockito 5.4.6 from annotations
// in hostr_sdk/mocks/usecase_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;

import 'package:hostr_sdk/hostr_sdk.dart' as _i7;
import 'package:hostr_sdk/usecase/escrow/supported_escrow_contract/supported_escrow_contract.dart'
    as _i15;
import 'package:hostr_sdk/usecase/nwc/nwc.cubit.dart' as _i14;
import 'package:hostr_sdk/usecase/payments/operations/pay_models.dart' as _i9;
import 'package:hostr_sdk/usecase/payments/operations/pay_operation.dart'
    as _i10;
import 'package:hostr_sdk/usecase/storage/storage.dart' as _i3;
import 'package:hostr_sdk/util/main.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:models/main.dart' as _i8;
import 'package:ndk/entities.dart' as _i13;
import 'package:ndk/ndk.dart' as _i2;
import 'package:ndk/shared/nips/nip01/key_pair.dart' as _i11;
import 'package:rxdart/rxdart.dart' as _i4;
import 'package:web3dart/web3dart.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNdk_0 extends _i1.SmartFake implements _i2.Ndk {
  _FakeNdk_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthStorage_1 extends _i1.SmartFake implements _i3.AuthStorage {
  _FakeAuthStorage_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeValueStream_2<T> extends _i1.SmartFake
    implements _i4.ValueStream<T> {
  _FakeValueStream_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEthPrivateKey_3 extends _i1.SmartFake implements _i5.EthPrivateKey {
  _FakeEthPrivateKey_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamWithStatus_4<T1> extends _i1.SmartFake
    implements _i6.StreamWithStatus<T1> {
  _FakeStreamWithStatus_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuth_5 extends _i1.SmartFake implements _i7.Auth {
  _FakeAuth_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCustomLogger_6 extends _i1.SmartFake implements _i6.CustomLogger {
  _FakeCustomLogger_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRequests_7 extends _i1.SmartFake implements _i7.Requests {
  _FakeRequests_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfileMetadata_8 extends _i1.SmartFake
    implements _i8.ProfileMetadata {
  _FakeProfileMetadata_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNwcStorage_9 extends _i1.SmartFake implements _i3.NwcStorage {
  _FakeNwcStorage_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNwcConnection_10 extends _i1.SmartFake implements _i2.NwcConnection {
  _FakeNwcConnection_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetInfoResponse_11 extends _i1.SmartFake
    implements _i2.GetInfoResponse {
  _FakeGetInfoResponse_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePayInvoiceResponse_12 extends _i1.SmartFake
    implements _i2.PayInvoiceResponse {
  _FakePayInvoiceResponse_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLookupInvoiceResponse_13 extends _i1.SmartFake
    implements _i2.LookupInvoiceResponse {
  _FakeLookupInvoiceResponse_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNwc_14 extends _i1.SmartFake implements _i7.Nwc {
  _FakeNwc_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeZapResponse_15 extends _i1.SmartFake implements _i2.ZapResponse {
  _FakeZapResponse_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeListing_16 extends _i1.SmartFake implements _i8.Listing {
  _FakeListing_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessaging_17 extends _i1.SmartFake implements _i7.Messaging {
  _FakeMessaging_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReservation_18 extends _i1.SmartFake implements _i8.Reservation {
  _FakeReservation_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEscrows_19 extends _i1.SmartFake implements _i7.Escrows {
  _FakeEscrows_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEscrowTrusts_20 extends _i1.SmartFake implements _i7.EscrowTrusts {
  _FakeEscrowTrusts_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEvm_21 extends _i1.SmartFake implements _i7.Evm {
  _FakeEvm_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEscrowFundOperation_22 extends _i1.SmartFake
    implements _i7.EscrowFundOperation {
  _FakeEscrowFundOperation_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEscrowMethods_23 extends _i1.SmartFake implements _i7.EscrowMethods {
  _FakeEscrowMethods_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMutualEscrowResult_24 extends _i1.SmartFake
    implements _i7.MutualEscrowResult {
  _FakeMutualEscrowResult_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEscrowService_25 extends _i1.SmartFake implements _i8.EscrowService {
  _FakeEscrowService_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEscrowTrust_26 extends _i1.SmartFake implements _i8.EscrowTrust {
  _FakeEscrowTrust_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEscrowMethod_27 extends _i1.SmartFake implements _i8.EscrowMethod {
  _FakeEscrowMethod_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBadgeDefinition_28 extends _i1.SmartFake
    implements _i8.BadgeDefinition {
  _FakeBadgeDefinition_28(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBadgeAward_29 extends _i1.SmartFake implements _i8.BadgeAward {
  _FakeBadgeAward_29(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeThreads_30 extends _i1.SmartFake implements _i7.Threads {
  _FakeThreads_30(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNip01Event_31 extends _i1.SmartFake implements _i2.Nip01Event {
  _FakeNip01Event_31(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMessage_32<T extends _i8.Event> extends _i1.SmartFake
    implements _i8.Message<T> {
  _FakeMessage_32(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReservationRequest_33 extends _i1.SmartFake
    implements _i8.ReservationRequest {
  _FakeReservationRequest_33(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeZaps_34 extends _i1.SmartFake implements _i7.Zaps {
  _FakeZaps_34(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEscrowUseCase_35 extends _i1.SmartFake implements _i7.EscrowUseCase {
  _FakeEscrowUseCase_35(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePayOperation_36<
  T extends _i9.PayParameters,
  RD extends _i9.ResolvedDetails,
  CD extends _i9.CallbackDetails,
  CmpD extends _i9.CompletedDetails
>
    extends _i1.SmartFake
    implements _i10.PayOperation<T, RD, CD, CmpD> {
  _FakePayOperation_36(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRootstock_37 extends _i1.SmartFake implements _i7.Rootstock {
  _FakeRootstock_37(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBitcoinAmount_38 extends _i1.SmartFake implements _i6.BitcoinAmount {
  _FakeBitcoinAmount_38(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEvmChain_39 extends _i1.SmartFake implements _i7.EvmChain {
  _FakeEvmChain_39(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRelayStorage_40 extends _i1.SmartFake implements _i3.RelayStorage {
  _FakeRelayStorage_40(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Auth].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuth extends _i1.Mock implements _i7.Auth {
  MockAuth() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Ndk get ndk =>
      (super.noSuchMethod(
            Invocation.getter(#ndk),
            returnValue: _FakeNdk_0(this, Invocation.getter(#ndk)),
          )
          as _i2.Ndk);

  @override
  _i3.AuthStorage get authStorage =>
      (super.noSuchMethod(
            Invocation.getter(#authStorage),
            returnValue: _FakeAuthStorage_1(
              this,
              Invocation.getter(#authStorage),
            ),
          )
          as _i3.AuthStorage);

  @override
  _i4.ValueStream<_i7.AuthState> get authState =>
      (super.noSuchMethod(
            Invocation.getter(#authState),
            returnValue: _FakeValueStream_2<_i7.AuthState>(
              this,
              Invocation.getter(#authState),
            ),
          )
          as _i4.ValueStream<_i7.AuthState>);

  @override
  set activeKeyPair(_i11.KeyPair? value) => super.noSuchMethod(
    Invocation.setter(#activeKeyPair, value),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> signup() =>
      (super.noSuchMethod(
            Invocation.method(#signup, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> signin(String? input) =>
      (super.noSuchMethod(
            Invocation.method(#signin, [input]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  bool ensureNdkAccountsMatch() =>
      (super.noSuchMethod(
            Invocation.method(#ensureNdkAccountsMatch, []),
            returnValue: false,
          )
          as bool);

  @override
  _i5.EthPrivateKey getActiveEvmKey() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveEvmKey, []),
            returnValue: _FakeEthPrivateKey_3(
              this,
              Invocation.method(#getActiveEvmKey, []),
            ),
          )
          as _i5.EthPrivateKey);

  @override
  _i12.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);
}

/// A class which mocks [Requests].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequests extends _i1.Mock implements _i7.Requests {
  MockRequests() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Ndk get ndk =>
      (super.noSuchMethod(
            Invocation.getter(#ndk),
            returnValue: _FakeNdk_0(this, Invocation.getter(#ndk)),
          )
          as _i2.Ndk);

  @override
  _i6.StreamWithStatus<T> subscribe<T extends _i2.Nip01Event>({
    required _i2.Filter? filter,
    List<String>? relays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [], {
              #filter: filter,
              #relays: relays,
            }),
            returnValue: _FakeStreamWithStatus_4<T>(
              this,
              Invocation.method(#subscribe, [], {
                #filter: filter,
                #relays: relays,
              }),
            ),
          )
          as _i6.StreamWithStatus<T>);

  @override
  _i12.Stream<T> query<T extends _i2.Nip01Event>({
    required _i2.Filter? filter,
    List<String>? relays,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#query, [], {
              #filter: filter,
              #relays: relays,
              #timeout: timeout,
            }),
            returnValue: _i12.Stream<T>.empty(),
          )
          as _i12.Stream<T>);

  @override
  _i12.Future<int> count({
    required _i2.Filter? filter,
    Duration? timeout,
    List<String>? relays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#count, [], {
              #filter: filter,
              #timeout: timeout,
              #relays: relays,
            }),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> broadcast({
    required _i2.Nip01Event? event,
    List<String>? relays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#broadcast, [], {#event: event, #relays: relays}),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<void> mock() =>
      (super.noSuchMethod(
            Invocation.method(#mock, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);
}

/// A class which mocks [MetadataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockMetadataUseCase extends _i1.Mock implements _i7.MetadataUseCase {
  MockMetadataUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Auth get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeAuth_5(this, Invocation.getter(#auth)),
          )
          as _i7.Auth);

  @override
  set auth(_i7.Auth? value) => super.noSuchMethod(
    Invocation.setter(#auth, value),
    returnValueForMissingStub: null,
  );

  @override
  _i6.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_6(this, Invocation.getter(#logger)),
          )
          as _i6.CustomLogger);

  @override
  _i7.Requests get requests =>
      (super.noSuchMethod(
            Invocation.getter(#requests),
            returnValue: _FakeRequests_7(this, Invocation.getter(#requests)),
          )
          as _i7.Requests);

  @override
  int get kind =>
      (super.noSuchMethod(Invocation.getter(#kind), returnValue: 0) as int);

  @override
  _i12.Future<_i8.ProfileMetadata?> loadMetadata(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#loadMetadata, [pubkey]),
            returnValue: _i12.Future<_i8.ProfileMetadata?>.value(),
          )
          as _i12.Future<_i8.ProfileMetadata?>);

  @override
  _i12.Future<_i12.Future<List<_i13.RelayBroadcastResponse>>>
  upsertMetadata() =>
      (super.noSuchMethod(
            Invocation.method(#upsertMetadata, []),
            returnValue:
                _i12.Future<
                  _i12.Future<List<_i13.RelayBroadcastResponse>>
                >.value(
                  _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
                    <_i13.RelayBroadcastResponse>[],
                  ),
                ),
          )
          as _i12.Future<_i12.Future<List<_i13.RelayBroadcastResponse>>>);

  @override
  _i6.StreamWithStatus<_i8.ProfileMetadata> subscribe(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [f]),
            returnValue: _FakeStreamWithStatus_4<_i8.ProfileMetadata>(
              this,
              Invocation.method(#subscribe, [f]),
            ),
          )
          as _i6.StreamWithStatus<_i8.ProfileMetadata>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> create(
    _i8.ProfileMetadata? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> update(
    _i8.ProfileMetadata? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> delete(
    _i8.ProfileMetadata? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i8.ProfileMetadata>> list(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#list, [f]),
            returnValue: _i12.Future<List<_i8.ProfileMetadata>>.value(
              <_i8.ProfileMetadata>[],
            ),
          )
          as _i12.Future<List<_i8.ProfileMetadata>>);

  @override
  _i12.Future<_i8.ProfileMetadata?> getOne(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#getOne, [f]),
            returnValue: _i12.Future<_i8.ProfileMetadata?>.value(),
          )
          as _i12.Future<_i8.ProfileMetadata?>);

  @override
  _i12.Future<_i8.ProfileMetadata?> getOneByDTag(String? d) =>
      (super.noSuchMethod(
            Invocation.method(#getOneByDTag, [d]),
            returnValue: _i12.Future<_i8.ProfileMetadata?>.value(),
          )
          as _i12.Future<_i8.ProfileMetadata?>);

  @override
  _i12.Future<_i8.ProfileMetadata> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i12.Future<_i8.ProfileMetadata>.value(
              _FakeProfileMetadata_8(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i12.Future<_i8.ProfileMetadata>);

  @override
  _i12.Future<int> count() =>
      (super.noSuchMethod(
            Invocation.method(#count, []),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);
}

/// A class which mocks [Nwc].
///
/// See the documentation for Mockito's code generation for more information.
class MockNwc extends _i1.Mock implements _i7.Nwc {
  MockNwc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_6(this, Invocation.getter(#logger)),
          )
          as _i6.CustomLogger);

  @override
  _i3.NwcStorage get nwcStorage =>
      (super.noSuchMethod(
            Invocation.getter(#nwcStorage),
            returnValue: _FakeNwcStorage_9(
              this,
              Invocation.getter(#nwcStorage),
            ),
          )
          as _i3.NwcStorage);

  @override
  _i2.Ndk get ndk =>
      (super.noSuchMethod(
            Invocation.getter(#ndk),
            returnValue: _FakeNdk_0(this, Invocation.getter(#ndk)),
          )
          as _i2.Ndk);

  @override
  List<_i14.NwcCubit> get connections =>
      (super.noSuchMethod(
            Invocation.getter(#connections),
            returnValue: <_i14.NwcCubit>[],
          )
          as List<_i14.NwcCubit>);

  @override
  _i12.Stream<List<_i14.NwcCubit>> get connectionsStream =>
      (super.noSuchMethod(
            Invocation.getter(#connectionsStream),
            returnValue: _i12.Stream<List<_i14.NwcCubit>>.empty(),
          )
          as _i12.Stream<List<_i14.NwcCubit>>);

  @override
  set nwcStorage(_i3.NwcStorage? value) => super.noSuchMethod(
    Invocation.setter(#nwcStorage, value),
    returnValueForMissingStub: null,
  );

  @override
  set ndk(_i2.Ndk? value) => super.noSuchMethod(
    Invocation.setter(#ndk, value),
    returnValueForMissingStub: null,
  );

  @override
  set connections(List<_i14.NwcCubit>? value) => super.noSuchMethod(
    Invocation.setter(#connections, value),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> save() =>
      (super.noSuchMethod(
            Invocation.method(#save, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> add(_i14.NwcCubit? reactiveConnection) =>
      (super.noSuchMethod(
            Invocation.method(#add, [reactiveConnection]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> remove(_i14.NwcCubit? reactiveConnection) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [reactiveConnection]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i2.NwcConnection> connect(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [url]),
            returnValue: _i12.Future<_i2.NwcConnection>.value(
              _FakeNwcConnection_10(this, Invocation.method(#connect, [url])),
            ),
          )
          as _i12.Future<_i2.NwcConnection>);

  @override
  _i12.Future<_i2.GetInfoResponse> getInfo(_i2.NwcConnection? connection) =>
      (super.noSuchMethod(
            Invocation.method(#getInfo, [connection]),
            returnValue: _i12.Future<_i2.GetInfoResponse>.value(
              _FakeGetInfoResponse_11(
                this,
                Invocation.method(#getInfo, [connection]),
              ),
            ),
          )
          as _i12.Future<_i2.GetInfoResponse>);

  @override
  _i12.Future<_i2.PayInvoiceResponse> payInvoice(
    _i2.NwcConnection? connection,
    String? invoice,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#payInvoice, [connection, invoice]),
            returnValue: _i12.Future<_i2.PayInvoiceResponse>.value(
              _FakePayInvoiceResponse_12(
                this,
                Invocation.method(#payInvoice, [connection, invoice]),
              ),
            ),
          )
          as _i12.Future<_i2.PayInvoiceResponse>);

  @override
  _i12.Future<_i2.LookupInvoiceResponse> lookupInvoice(
    _i2.NwcConnection? connection, {
    String? paymentHash,
    String? invoice,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #lookupInvoice,
              [connection],
              {#paymentHash: paymentHash, #invoice: invoice},
            ),
            returnValue: _i12.Future<_i2.LookupInvoiceResponse>.value(
              _FakeLookupInvoiceResponse_13(
                this,
                Invocation.method(
                  #lookupInvoice,
                  [connection],
                  {#paymentHash: paymentHash, #invoice: invoice},
                ),
              ),
            ),
          )
          as _i12.Future<_i2.LookupInvoiceResponse>);

  @override
  _i12.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void start() => super.noSuchMethod(
    Invocation.method(#start, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [Zaps].
///
/// See the documentation for Mockito's code generation for more information.
class MockZaps extends _i1.Mock implements _i7.Zaps {
  MockZaps() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Nwc get nwc =>
      (super.noSuchMethod(
            Invocation.getter(#nwc),
            returnValue: _FakeNwc_14(this, Invocation.getter(#nwc)),
          )
          as _i7.Nwc);

  @override
  _i2.Ndk get ndk =>
      (super.noSuchMethod(
            Invocation.getter(#ndk),
            returnValue: _FakeNdk_0(this, Invocation.getter(#ndk)),
          )
          as _i2.Ndk);

  @override
  set nwc(_i7.Nwc? value) => super.noSuchMethod(
    Invocation.setter(#nwc, value),
    returnValueForMissingStub: null,
  );

  @override
  set ndk(_i2.Ndk? value) => super.noSuchMethod(
    Invocation.setter(#ndk, value),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<_i2.ZapResponse> zap({
    required String? lnurl,
    required int? amountSats,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#zap, [], {
              #lnurl: lnurl,
              #amountSats: amountSats,
            }),
            returnValue: _i12.Future<_i2.ZapResponse>.value(
              _FakeZapResponse_15(
                this,
                Invocation.method(#zap, [], {
                  #lnurl: lnurl,
                  #amountSats: amountSats,
                }),
              ),
            ),
          )
          as _i12.Future<_i2.ZapResponse>);

  @override
  _i12.Future<_i2.InvoiceResponse?> fetchInvoice({
    required String? lud16Link,
    required int? amountSats,
    _i2.ZapRequest? zapRequest,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchInvoice, [], {
              #lud16Link: lud16Link,
              #amountSats: amountSats,
              #zapRequest: zapRequest,
            }),
            returnValue: _i12.Future<_i2.InvoiceResponse?>.value(),
          )
          as _i12.Future<_i2.InvoiceResponse?>);

  @override
  _i6.StreamWithStatus<_i2.Nip01Event> subscribeZapReceipts({
    required String? pubkey,
    String? eventId,
    String? addressableId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeZapReceipts, [], {
              #pubkey: pubkey,
              #eventId: eventId,
              #addressableId: addressableId,
            }),
            returnValue: _FakeStreamWithStatus_4<_i2.Nip01Event>(
              this,
              Invocation.method(#subscribeZapReceipts, [], {
                #pubkey: pubkey,
                #eventId: eventId,
                #addressableId: addressableId,
              }),
            ),
          )
          as _i6.StreamWithStatus<_i2.Nip01Event>);
}

/// A class which mocks [Listings].
///
/// See the documentation for Mockito's code generation for more information.
class MockListings extends _i1.Mock implements _i7.Listings {
  MockListings() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_6(this, Invocation.getter(#logger)),
          )
          as _i6.CustomLogger);

  @override
  _i7.Requests get requests =>
      (super.noSuchMethod(
            Invocation.getter(#requests),
            returnValue: _FakeRequests_7(this, Invocation.getter(#requests)),
          )
          as _i7.Requests);

  @override
  int get kind =>
      (super.noSuchMethod(Invocation.getter(#kind), returnValue: 0) as int);

  @override
  _i6.StreamWithStatus<_i8.Listing> subscribe(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [f]),
            returnValue: _FakeStreamWithStatus_4<_i8.Listing>(
              this,
              Invocation.method(#subscribe, [f]),
            ),
          )
          as _i6.StreamWithStatus<_i8.Listing>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> create(_i8.Listing? event) =>
      (super.noSuchMethod(
            Invocation.method(#create, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> update(_i8.Listing? event) =>
      (super.noSuchMethod(
            Invocation.method(#update, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> delete(_i8.Listing? event) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i8.Listing>> list(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#list, [f]),
            returnValue: _i12.Future<List<_i8.Listing>>.value(<_i8.Listing>[]),
          )
          as _i12.Future<List<_i8.Listing>>);

  @override
  _i12.Future<_i8.Listing?> getOne(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#getOne, [f]),
            returnValue: _i12.Future<_i8.Listing?>.value(),
          )
          as _i12.Future<_i8.Listing?>);

  @override
  _i12.Future<_i8.Listing?> getOneByDTag(String? d) =>
      (super.noSuchMethod(
            Invocation.method(#getOneByDTag, [d]),
            returnValue: _i12.Future<_i8.Listing?>.value(),
          )
          as _i12.Future<_i8.Listing?>);

  @override
  _i12.Future<_i8.Listing> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i12.Future<_i8.Listing>.value(
              _FakeListing_16(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i12.Future<_i8.Listing>);

  @override
  _i12.Future<int> count() =>
      (super.noSuchMethod(
            Invocation.method(#count, []),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);
}

/// A class which mocks [Reservations].
///
/// See the documentation for Mockito's code generation for more information.
class MockReservations extends _i1.Mock implements _i7.Reservations {
  MockReservations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Messaging get messaging =>
      (super.noSuchMethod(
            Invocation.getter(#messaging),
            returnValue: _FakeMessaging_17(this, Invocation.getter(#messaging)),
          )
          as _i7.Messaging);

  @override
  _i7.Auth get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeAuth_5(this, Invocation.getter(#auth)),
          )
          as _i7.Auth);

  @override
  _i6.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_6(this, Invocation.getter(#logger)),
          )
          as _i6.CustomLogger);

  @override
  _i7.Requests get requests =>
      (super.noSuchMethod(
            Invocation.getter(#requests),
            returnValue: _FakeRequests_7(this, Invocation.getter(#requests)),
          )
          as _i7.Requests);

  @override
  int get kind =>
      (super.noSuchMethod(Invocation.getter(#kind), returnValue: 0) as int);

  @override
  _i12.Future<List<_i8.Reservation>> getListingReservations({
    required String? listingAnchor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getListingReservations, [], {
              #listingAnchor: listingAnchor,
            }),
            returnValue: _i12.Future<List<_i8.Reservation>>.value(
              <_i8.Reservation>[],
            ),
          )
          as _i12.Future<List<_i8.Reservation>>);

  @override
  _i6.StreamWithStatus<_i8.Reservation> subscribeToMyReservations() =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToMyReservations, []),
            returnValue: _FakeStreamWithStatus_4<_i8.Reservation>(
              this,
              Invocation.method(#subscribeToMyReservations, []),
            ),
          )
          as _i6.StreamWithStatus<_i8.Reservation>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> accept(
    _i8.Message<_i8.Event>? message,
    _i8.ReservationRequest? request,
    String? guestPubkey,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#accept, [message, request, guestPubkey]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<_i8.Reservation> createSelfSigned({
    required String? threadId,
    required _i8.ReservationRequest? reservationRequest,
    required _i8.SelfSignedProof? proof,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSelfSigned, [], {
              #threadId: threadId,
              #reservationRequest: reservationRequest,
              #proof: proof,
            }),
            returnValue: _i12.Future<_i8.Reservation>.value(
              _FakeReservation_18(
                this,
                Invocation.method(#createSelfSigned, [], {
                  #threadId: threadId,
                  #reservationRequest: reservationRequest,
                  #proof: proof,
                }),
              ),
            ),
          )
          as _i12.Future<_i8.Reservation>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.StreamWithStatus<_i8.Reservation> subscribe(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [f]),
            returnValue: _FakeStreamWithStatus_4<_i8.Reservation>(
              this,
              Invocation.method(#subscribe, [f]),
            ),
          )
          as _i6.StreamWithStatus<_i8.Reservation>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> create(
    _i8.Reservation? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> update(
    _i8.Reservation? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> delete(
    _i8.Reservation? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i8.Reservation>> list(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#list, [f]),
            returnValue: _i12.Future<List<_i8.Reservation>>.value(
              <_i8.Reservation>[],
            ),
          )
          as _i12.Future<List<_i8.Reservation>>);

  @override
  _i12.Future<_i8.Reservation?> getOne(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#getOne, [f]),
            returnValue: _i12.Future<_i8.Reservation?>.value(),
          )
          as _i12.Future<_i8.Reservation?>);

  @override
  _i12.Future<_i8.Reservation?> getOneByDTag(String? d) =>
      (super.noSuchMethod(
            Invocation.method(#getOneByDTag, [d]),
            returnValue: _i12.Future<_i8.Reservation?>.value(),
          )
          as _i12.Future<_i8.Reservation?>);

  @override
  _i12.Future<_i8.Reservation> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i12.Future<_i8.Reservation>.value(
              _FakeReservation_18(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i12.Future<_i8.Reservation>);

  @override
  _i12.Future<int> count() =>
      (super.noSuchMethod(
            Invocation.method(#count, []),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);
}

/// A class which mocks [EscrowUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEscrowUseCase extends _i1.Mock implements _i7.EscrowUseCase {
  MockEscrowUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_6(this, Invocation.getter(#logger)),
          )
          as _i6.CustomLogger);

  @override
  _i7.Auth get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeAuth_5(this, Invocation.getter(#auth)),
          )
          as _i7.Auth);

  @override
  _i7.Escrows get escrows =>
      (super.noSuchMethod(
            Invocation.getter(#escrows),
            returnValue: _FakeEscrows_19(this, Invocation.getter(#escrows)),
          )
          as _i7.Escrows);

  @override
  _i7.EscrowTrusts get escrowTrusts =>
      (super.noSuchMethod(
            Invocation.getter(#escrowTrusts),
            returnValue: _FakeEscrowTrusts_20(
              this,
              Invocation.getter(#escrowTrusts),
            ),
          )
          as _i7.EscrowTrusts);

  @override
  _i7.Evm get evm =>
      (super.noSuchMethod(
            Invocation.getter(#evm),
            returnValue: _FakeEvm_21(this, Invocation.getter(#evm)),
          )
          as _i7.Evm);

  @override
  _i7.EscrowFundOperation fund(_i7.EscrowFundParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#fund, [params]),
            returnValue: _FakeEscrowFundOperation_22(
              this,
              Invocation.method(#fund, [params]),
            ),
          )
          as _i7.EscrowFundOperation);

  @override
  _i6.StreamWithStatus<_i15.FundedEvent> checkEscrowStatus(
    _i8.EscrowServiceSelected? selectedEscrow,
    String? tradeId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkEscrowStatus, [selectedEscrow, tradeId]),
            returnValue: _FakeStreamWithStatus_4<_i15.FundedEvent>(
              this,
              Invocation.method(#checkEscrowStatus, [selectedEscrow, tradeId]),
            ),
          )
          as _i6.StreamWithStatus<_i15.FundedEvent>);

  @override
  _i6.StreamWithStatus<_i8.EscrowProof> getEscrowProof(
    _i8.EscrowServiceSelected? selectedEscrow,
    String? tradeId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEscrowProof, [selectedEscrow, tradeId]),
            returnValue: _FakeStreamWithStatus_4<_i8.EscrowProof>(
              this,
              Invocation.method(#getEscrowProof, [selectedEscrow, tradeId]),
            ),
          )
          as _i6.StreamWithStatus<_i8.EscrowProof>);
}

/// A class which mocks [Escrows].
///
/// See the documentation for Mockito's code generation for more information.
class MockEscrows extends _i1.Mock implements _i7.Escrows {
  MockEscrows() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.EscrowMethods get escrowMethods =>
      (super.noSuchMethod(
            Invocation.getter(#escrowMethods),
            returnValue: _FakeEscrowMethods_23(
              this,
              Invocation.getter(#escrowMethods),
            ),
          )
          as _i7.EscrowMethods);

  @override
  _i7.EscrowTrusts get escrowTrusts =>
      (super.noSuchMethod(
            Invocation.getter(#escrowTrusts),
            returnValue: _FakeEscrowTrusts_20(
              this,
              Invocation.getter(#escrowTrusts),
            ),
          )
          as _i7.EscrowTrusts);

  @override
  set escrowMethods(_i7.EscrowMethods? value) => super.noSuchMethod(
    Invocation.setter(#escrowMethods, value),
    returnValueForMissingStub: null,
  );

  @override
  set escrowTrusts(_i7.EscrowTrusts? value) => super.noSuchMethod(
    Invocation.setter(#escrowTrusts, value),
    returnValueForMissingStub: null,
  );

  @override
  _i6.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_6(this, Invocation.getter(#logger)),
          )
          as _i6.CustomLogger);

  @override
  _i7.Requests get requests =>
      (super.noSuchMethod(
            Invocation.getter(#requests),
            returnValue: _FakeRequests_7(this, Invocation.getter(#requests)),
          )
          as _i7.Requests);

  @override
  int get kind =>
      (super.noSuchMethod(Invocation.getter(#kind), returnValue: 0) as int);

  @override
  _i12.Future<_i7.MutualEscrowResult> determineMutualEscrow(
    String? pubkey1,
    String? pubkey2,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#determineMutualEscrow, [pubkey1, pubkey2]),
            returnValue: _i12.Future<_i7.MutualEscrowResult>.value(
              _FakeMutualEscrowResult_24(
                this,
                Invocation.method(#determineMutualEscrow, [pubkey1, pubkey2]),
              ),
            ),
          )
          as _i12.Future<_i7.MutualEscrowResult>);

  @override
  _i6.StreamWithStatus<_i8.EscrowService> subscribe(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [f]),
            returnValue: _FakeStreamWithStatus_4<_i8.EscrowService>(
              this,
              Invocation.method(#subscribe, [f]),
            ),
          )
          as _i6.StreamWithStatus<_i8.EscrowService>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> create(
    _i8.EscrowService? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> update(
    _i8.EscrowService? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> delete(
    _i8.EscrowService? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i8.EscrowService>> list(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#list, [f]),
            returnValue: _i12.Future<List<_i8.EscrowService>>.value(
              <_i8.EscrowService>[],
            ),
          )
          as _i12.Future<List<_i8.EscrowService>>);

  @override
  _i12.Future<_i8.EscrowService?> getOne(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#getOne, [f]),
            returnValue: _i12.Future<_i8.EscrowService?>.value(),
          )
          as _i12.Future<_i8.EscrowService?>);

  @override
  _i12.Future<_i8.EscrowService?> getOneByDTag(String? d) =>
      (super.noSuchMethod(
            Invocation.method(#getOneByDTag, [d]),
            returnValue: _i12.Future<_i8.EscrowService?>.value(),
          )
          as _i12.Future<_i8.EscrowService?>);

  @override
  _i12.Future<_i8.EscrowService> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i12.Future<_i8.EscrowService>.value(
              _FakeEscrowService_25(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i12.Future<_i8.EscrowService>);

  @override
  _i12.Future<int> count() =>
      (super.noSuchMethod(
            Invocation.method(#count, []),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);
}

/// A class which mocks [EscrowTrusts].
///
/// See the documentation for Mockito's code generation for more information.
class MockEscrowTrusts extends _i1.Mock implements _i7.EscrowTrusts {
  MockEscrowTrusts() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Auth get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeAuth_5(this, Invocation.getter(#auth)),
          )
          as _i7.Auth);

  @override
  _i6.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_6(this, Invocation.getter(#logger)),
          )
          as _i6.CustomLogger);

  @override
  _i7.Requests get requests =>
      (super.noSuchMethod(
            Invocation.getter(#requests),
            returnValue: _FakeRequests_7(this, Invocation.getter(#requests)),
          )
          as _i7.Requests);

  @override
  int get kind =>
      (super.noSuchMethod(Invocation.getter(#kind), returnValue: 0) as int);

  @override
  _i12.Future<_i8.EscrowTrust?> trusted(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#trusted, [pubkey]),
            returnValue: _i12.Future<_i8.EscrowTrust?>.value(),
          )
          as _i12.Future<_i8.EscrowTrust?>);

  @override
  _i12.Future<_i8.EscrowTrust?> myTrusted() =>
      (super.noSuchMethod(
            Invocation.method(#myTrusted, []),
            returnValue: _i12.Future<_i8.EscrowTrust?>.value(),
          )
          as _i12.Future<_i8.EscrowTrust?>);

  @override
  _i6.StreamWithStatus<_i8.EscrowTrust> subscribe(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [f]),
            returnValue: _FakeStreamWithStatus_4<_i8.EscrowTrust>(
              this,
              Invocation.method(#subscribe, [f]),
            ),
          )
          as _i6.StreamWithStatus<_i8.EscrowTrust>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> create(
    _i8.EscrowTrust? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> update(
    _i8.EscrowTrust? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> delete(
    _i8.EscrowTrust? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i8.EscrowTrust>> list(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#list, [f]),
            returnValue: _i12.Future<List<_i8.EscrowTrust>>.value(
              <_i8.EscrowTrust>[],
            ),
          )
          as _i12.Future<List<_i8.EscrowTrust>>);

  @override
  _i12.Future<_i8.EscrowTrust?> getOne(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#getOne, [f]),
            returnValue: _i12.Future<_i8.EscrowTrust?>.value(),
          )
          as _i12.Future<_i8.EscrowTrust?>);

  @override
  _i12.Future<_i8.EscrowTrust?> getOneByDTag(String? d) =>
      (super.noSuchMethod(
            Invocation.method(#getOneByDTag, [d]),
            returnValue: _i12.Future<_i8.EscrowTrust?>.value(),
          )
          as _i12.Future<_i8.EscrowTrust?>);

  @override
  _i12.Future<_i8.EscrowTrust> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i12.Future<_i8.EscrowTrust>.value(
              _FakeEscrowTrust_26(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i12.Future<_i8.EscrowTrust>);

  @override
  _i12.Future<int> count() =>
      (super.noSuchMethod(
            Invocation.method(#count, []),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);
}

/// A class which mocks [EscrowMethods].
///
/// See the documentation for Mockito's code generation for more information.
class MockEscrowMethods extends _i1.Mock implements _i7.EscrowMethods {
  MockEscrowMethods() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_6(this, Invocation.getter(#logger)),
          )
          as _i6.CustomLogger);

  @override
  _i7.Requests get requests =>
      (super.noSuchMethod(
            Invocation.getter(#requests),
            returnValue: _FakeRequests_7(this, Invocation.getter(#requests)),
          )
          as _i7.Requests);

  @override
  int get kind =>
      (super.noSuchMethod(Invocation.getter(#kind), returnValue: 0) as int);

  @override
  _i6.StreamWithStatus<_i8.EscrowMethod> subscribe(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [f]),
            returnValue: _FakeStreamWithStatus_4<_i8.EscrowMethod>(
              this,
              Invocation.method(#subscribe, [f]),
            ),
          )
          as _i6.StreamWithStatus<_i8.EscrowMethod>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> create(
    _i8.EscrowMethod? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> update(
    _i8.EscrowMethod? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> delete(
    _i8.EscrowMethod? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i8.EscrowMethod>> list(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#list, [f]),
            returnValue: _i12.Future<List<_i8.EscrowMethod>>.value(
              <_i8.EscrowMethod>[],
            ),
          )
          as _i12.Future<List<_i8.EscrowMethod>>);

  @override
  _i12.Future<_i8.EscrowMethod?> getOne(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#getOne, [f]),
            returnValue: _i12.Future<_i8.EscrowMethod?>.value(),
          )
          as _i12.Future<_i8.EscrowMethod?>);

  @override
  _i12.Future<_i8.EscrowMethod?> getOneByDTag(String? d) =>
      (super.noSuchMethod(
            Invocation.method(#getOneByDTag, [d]),
            returnValue: _i12.Future<_i8.EscrowMethod?>.value(),
          )
          as _i12.Future<_i8.EscrowMethod?>);

  @override
  _i12.Future<_i8.EscrowMethod> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i12.Future<_i8.EscrowMethod>.value(
              _FakeEscrowMethod_27(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i12.Future<_i8.EscrowMethod>);

  @override
  _i12.Future<int> count() =>
      (super.noSuchMethod(
            Invocation.method(#count, []),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);
}

/// A class which mocks [BadgeDefinitions].
///
/// See the documentation for Mockito's code generation for more information.
class MockBadgeDefinitions extends _i1.Mock implements _i7.BadgeDefinitions {
  MockBadgeDefinitions() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_6(this, Invocation.getter(#logger)),
          )
          as _i6.CustomLogger);

  @override
  _i7.Requests get requests =>
      (super.noSuchMethod(
            Invocation.getter(#requests),
            returnValue: _FakeRequests_7(this, Invocation.getter(#requests)),
          )
          as _i7.Requests);

  @override
  int get kind =>
      (super.noSuchMethod(Invocation.getter(#kind), returnValue: 0) as int);

  @override
  _i6.StreamWithStatus<_i8.BadgeDefinition> subscribe(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [f]),
            returnValue: _FakeStreamWithStatus_4<_i8.BadgeDefinition>(
              this,
              Invocation.method(#subscribe, [f]),
            ),
          )
          as _i6.StreamWithStatus<_i8.BadgeDefinition>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> create(
    _i8.BadgeDefinition? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> update(
    _i8.BadgeDefinition? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> delete(
    _i8.BadgeDefinition? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i8.BadgeDefinition>> list(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#list, [f]),
            returnValue: _i12.Future<List<_i8.BadgeDefinition>>.value(
              <_i8.BadgeDefinition>[],
            ),
          )
          as _i12.Future<List<_i8.BadgeDefinition>>);

  @override
  _i12.Future<_i8.BadgeDefinition?> getOne(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#getOne, [f]),
            returnValue: _i12.Future<_i8.BadgeDefinition?>.value(),
          )
          as _i12.Future<_i8.BadgeDefinition?>);

  @override
  _i12.Future<_i8.BadgeDefinition?> getOneByDTag(String? d) =>
      (super.noSuchMethod(
            Invocation.method(#getOneByDTag, [d]),
            returnValue: _i12.Future<_i8.BadgeDefinition?>.value(),
          )
          as _i12.Future<_i8.BadgeDefinition?>);

  @override
  _i12.Future<_i8.BadgeDefinition> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i12.Future<_i8.BadgeDefinition>.value(
              _FakeBadgeDefinition_28(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i12.Future<_i8.BadgeDefinition>);

  @override
  _i12.Future<int> count() =>
      (super.noSuchMethod(
            Invocation.method(#count, []),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);
}

/// A class which mocks [BadgeAwards].
///
/// See the documentation for Mockito's code generation for more information.
class MockBadgeAwards extends _i1.Mock implements _i7.BadgeAwards {
  MockBadgeAwards() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_6(this, Invocation.getter(#logger)),
          )
          as _i6.CustomLogger);

  @override
  _i7.Requests get requests =>
      (super.noSuchMethod(
            Invocation.getter(#requests),
            returnValue: _FakeRequests_7(this, Invocation.getter(#requests)),
          )
          as _i7.Requests);

  @override
  int get kind =>
      (super.noSuchMethod(Invocation.getter(#kind), returnValue: 0) as int);

  @override
  _i6.StreamWithStatus<_i8.BadgeAward> subscribe(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [f]),
            returnValue: _FakeStreamWithStatus_4<_i8.BadgeAward>(
              this,
              Invocation.method(#subscribe, [f]),
            ),
          )
          as _i6.StreamWithStatus<_i8.BadgeAward>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> create(
    _i8.BadgeAward? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> update(
    _i8.BadgeAward? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> delete(
    _i8.BadgeAward? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i8.BadgeAward>> list(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#list, [f]),
            returnValue: _i12.Future<List<_i8.BadgeAward>>.value(
              <_i8.BadgeAward>[],
            ),
          )
          as _i12.Future<List<_i8.BadgeAward>>);

  @override
  _i12.Future<_i8.BadgeAward?> getOne(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#getOne, [f]),
            returnValue: _i12.Future<_i8.BadgeAward?>.value(),
          )
          as _i12.Future<_i8.BadgeAward?>);

  @override
  _i12.Future<_i8.BadgeAward?> getOneByDTag(String? d) =>
      (super.noSuchMethod(
            Invocation.method(#getOneByDTag, [d]),
            returnValue: _i12.Future<_i8.BadgeAward?>.value(),
          )
          as _i12.Future<_i8.BadgeAward?>);

  @override
  _i12.Future<_i8.BadgeAward> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i12.Future<_i8.BadgeAward>.value(
              _FakeBadgeAward_29(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i12.Future<_i8.BadgeAward>);

  @override
  _i12.Future<int> count() =>
      (super.noSuchMethod(
            Invocation.method(#count, []),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);
}

/// A class which mocks [Messaging].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessaging extends _i1.Mock implements _i7.Messaging {
  MockMessaging() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Ndk get ndk =>
      (super.noSuchMethod(
            Invocation.getter(#ndk),
            returnValue: _FakeNdk_0(this, Invocation.getter(#ndk)),
          )
          as _i2.Ndk);

  @override
  _i7.Requests get requests =>
      (super.noSuchMethod(
            Invocation.getter(#requests),
            returnValue: _FakeRequests_7(this, Invocation.getter(#requests)),
          )
          as _i7.Requests);

  @override
  _i6.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_6(this, Invocation.getter(#logger)),
          )
          as _i6.CustomLogger);

  @override
  _i7.Threads get threads =>
      (super.noSuchMethod(
            Invocation.getter(#threads),
            returnValue: _FakeThreads_30(this, Invocation.getter(#threads)),
          )
          as _i7.Threads);

  @override
  _i12.Future<_i2.Nip01Event> getRumour(
    String? content,
    List<List<String>>? tags,
    List<String>? recipientPubkeys,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRumour, [content, tags, recipientPubkeys]),
            returnValue: _i12.Future<_i2.Nip01Event>.value(
              _FakeNip01Event_31(
                this,
                Invocation.method(#getRumour, [
                  content,
                  tags,
                  recipientPubkeys,
                ]),
              ),
            ),
          )
          as _i12.Future<_i2.Nip01Event>);

  @override
  _i12.Future<_i8.Message<_i8.Event>> broadcastTextAndAwait({
    required String? content,
    required List<List<String>>? tags,
    required List<String>? recipientPubkeys,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastTextAndAwait, [], {
              #content: content,
              #tags: tags,
              #recipientPubkeys: recipientPubkeys,
            }),
            returnValue: _i12.Future<_i8.Message<_i8.Event>>.value(
              _FakeMessage_32<_i8.Event>(
                this,
                Invocation.method(#broadcastTextAndAwait, [], {
                  #content: content,
                  #tags: tags,
                  #recipientPubkeys: recipientPubkeys,
                }),
              ),
            ),
          )
          as _i12.Future<_i8.Message<_i8.Event>>);

  @override
  _i12.Future<List<_i12.Future<List<_i13.RelayBroadcastResponse>>>>
  broadcastText({
    required String? content,
    required List<List<String>>? tags,
    required List<String>? recipientPubkeys,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastText, [], {
              #content: content,
              #tags: tags,
              #recipientPubkeys: recipientPubkeys,
            }),
            returnValue:
                _i12.Future<
                  List<_i12.Future<List<_i13.RelayBroadcastResponse>>>
                >.value(<_i12.Future<List<_i13.RelayBroadcastResponse>>>[]),
          )
          as _i12.Future<List<_i12.Future<List<_i13.RelayBroadcastResponse>>>>);

  @override
  _i12.Future<_i8.Message<_i8.Event>> broadcastEventAndWait({
    required _i2.Nip01Event? event,
    required List<List<String>>? tags,
    required List<String>? recipientPubkeys,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastEventAndWait, [], {
              #event: event,
              #tags: tags,
              #recipientPubkeys: recipientPubkeys,
            }),
            returnValue: _i12.Future<_i8.Message<_i8.Event>>.value(
              _FakeMessage_32<_i8.Event>(
                this,
                Invocation.method(#broadcastEventAndWait, [], {
                  #event: event,
                  #tags: tags,
                  #recipientPubkeys: recipientPubkeys,
                }),
              ),
            ),
          )
          as _i12.Future<_i8.Message<_i8.Event>>);

  @override
  _i12.Future<List<_i12.Future<List<_i13.RelayBroadcastResponse>>>>
  broadcastEvent({
    required _i2.Nip01Event? event,
    required List<List<String>>? tags,
    required List<String>? recipientPubkeys,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastEvent, [], {
              #event: event,
              #tags: tags,
              #recipientPubkeys: recipientPubkeys,
            }),
            returnValue:
                _i12.Future<
                  List<_i12.Future<List<_i13.RelayBroadcastResponse>>>
                >.value(<_i12.Future<List<_i13.RelayBroadcastResponse>>>[]),
          )
          as _i12.Future<List<_i12.Future<List<_i13.RelayBroadcastResponse>>>>);
}

/// A class which mocks [ReservationRequests].
///
/// See the documentation for Mockito's code generation for more information.
class MockReservationRequests extends _i1.Mock
    implements _i7.ReservationRequests {
  MockReservationRequests() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Ndk get ndk =>
      (super.noSuchMethod(
            Invocation.getter(#ndk),
            returnValue: _FakeNdk_0(this, Invocation.getter(#ndk)),
          )
          as _i2.Ndk);

  @override
  _i6.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_6(this, Invocation.getter(#logger)),
          )
          as _i6.CustomLogger);

  @override
  _i7.Requests get requests =>
      (super.noSuchMethod(
            Invocation.getter(#requests),
            returnValue: _FakeRequests_7(this, Invocation.getter(#requests)),
          )
          as _i7.Requests);

  @override
  int get kind =>
      (super.noSuchMethod(Invocation.getter(#kind), returnValue: 0) as int);

  @override
  _i12.Future<_i8.ReservationRequest> createReservationRequest({
    required _i8.Listing? listing,
    required DateTime? startDate,
    required DateTime? endDate,
    required String? recipientPubkey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createReservationRequest, [], {
              #listing: listing,
              #startDate: startDate,
              #endDate: endDate,
              #recipientPubkey: recipientPubkey,
            }),
            returnValue: _i12.Future<_i8.ReservationRequest>.value(
              _FakeReservationRequest_33(
                this,
                Invocation.method(#createReservationRequest, [], {
                  #listing: listing,
                  #startDate: startDate,
                  #endDate: endDate,
                  #recipientPubkey: recipientPubkey,
                }),
              ),
            ),
          )
          as _i12.Future<_i8.ReservationRequest>);

  @override
  _i6.StreamWithStatus<_i2.Nip01Event> subscribe(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [f]),
            returnValue: _FakeStreamWithStatus_4<_i2.Nip01Event>(
              this,
              Invocation.method(#subscribe, [f]),
            ),
          )
          as _i6.StreamWithStatus<_i2.Nip01Event>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> create(
    _i2.Nip01Event? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#create, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> update(
    _i2.Nip01Event? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i13.RelayBroadcastResponse>> delete(
    _i2.Nip01Event? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [event]),
            returnValue: _i12.Future<List<_i13.RelayBroadcastResponse>>.value(
              <_i13.RelayBroadcastResponse>[],
            ),
          )
          as _i12.Future<List<_i13.RelayBroadcastResponse>>);

  @override
  _i12.Future<List<_i2.Nip01Event>> list(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#list, [f]),
            returnValue: _i12.Future<List<_i2.Nip01Event>>.value(
              <_i2.Nip01Event>[],
            ),
          )
          as _i12.Future<List<_i2.Nip01Event>>);

  @override
  _i12.Future<_i2.Nip01Event?> getOne(_i2.Filter? f) =>
      (super.noSuchMethod(
            Invocation.method(#getOne, [f]),
            returnValue: _i12.Future<_i2.Nip01Event?>.value(),
          )
          as _i12.Future<_i2.Nip01Event?>);

  @override
  _i12.Future<_i2.Nip01Event?> getOneByDTag(String? d) =>
      (super.noSuchMethod(
            Invocation.method(#getOneByDTag, [d]),
            returnValue: _i12.Future<_i2.Nip01Event?>.value(),
          )
          as _i12.Future<_i2.Nip01Event?>);

  @override
  _i12.Future<_i2.Nip01Event> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i12.Future<_i2.Nip01Event>.value(
              _FakeNip01Event_31(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i12.Future<_i2.Nip01Event>);

  @override
  _i12.Future<int> count() =>
      (super.noSuchMethod(
            Invocation.method(#count, []),
            returnValue: _i12.Future<int>.value(0),
          )
          as _i12.Future<int>);
}

/// A class which mocks [Payments].
///
/// See the documentation for Mockito's code generation for more information.
class MockPayments extends _i1.Mock implements _i7.Payments {
  MockPayments() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_6(this, Invocation.getter(#logger)),
          )
          as _i6.CustomLogger);

  @override
  _i7.Zaps get zaps =>
      (super.noSuchMethod(
            Invocation.getter(#zaps),
            returnValue: _FakeZaps_34(this, Invocation.getter(#zaps)),
          )
          as _i7.Zaps);

  @override
  _i7.Nwc get nwc =>
      (super.noSuchMethod(
            Invocation.getter(#nwc),
            returnValue: _FakeNwc_14(this, Invocation.getter(#nwc)),
          )
          as _i7.Nwc);

  @override
  _i7.EscrowUseCase get escrow =>
      (super.noSuchMethod(
            Invocation.getter(#escrow),
            returnValue: _FakeEscrowUseCase_35(
              this,
              Invocation.getter(#escrow),
            ),
          )
          as _i7.EscrowUseCase);

  @override
  set zaps(_i7.Zaps? value) => super.noSuchMethod(
    Invocation.setter(#zaps, value),
    returnValueForMissingStub: null,
  );

  @override
  set nwc(_i7.Nwc? value) => super.noSuchMethod(
    Invocation.setter(#nwc, value),
    returnValueForMissingStub: null,
  );

  @override
  _i10.PayOperation<
    _i9.PayParameters,
    _i9.ResolvedDetails,
    _i9.CallbackDetails,
    _i9.CompletedDetails
  >
  pay(_i9.PayParameters? params) =>
      (super.noSuchMethod(
            Invocation.method(#pay, [params]),
            returnValue:
                _FakePayOperation_36<
                  _i9.PayParameters,
                  _i9.ResolvedDetails,
                  _i9.CallbackDetails,
                  _i9.CompletedDetails
                >(this, Invocation.method(#pay, [params])),
          )
          as _i10.PayOperation<
            _i9.PayParameters,
            _i9.ResolvedDetails,
            _i9.CallbackDetails,
            _i9.CompletedDetails
          >);
}

/// A class which mocks [Evm].
///
/// See the documentation for Mockito's code generation for more information.
class MockEvm extends _i1.Mock implements _i7.Evm {
  MockEvm() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_6(this, Invocation.getter(#logger)),
          )
          as _i6.CustomLogger);

  @override
  _i7.Auth get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeAuth_5(this, Invocation.getter(#auth)),
          )
          as _i7.Auth);

  @override
  _i7.Rootstock get rootstock =>
      (super.noSuchMethod(
            Invocation.getter(#rootstock),
            returnValue: _FakeRootstock_37(this, Invocation.getter(#rootstock)),
          )
          as _i7.Rootstock);

  @override
  List<_i7.EvmChain> get supportedEvmChains =>
      (super.noSuchMethod(
            Invocation.getter(#supportedEvmChains),
            returnValue: <_i7.EvmChain>[],
          )
          as List<_i7.EvmChain>);

  @override
  set supportedEvmChains(List<_i7.EvmChain>? value) => super.noSuchMethod(
    Invocation.setter(#supportedEvmChains, value),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<_i6.BitcoinAmount> getBalance() =>
      (super.noSuchMethod(
            Invocation.method(#getBalance, []),
            returnValue: _i12.Future<_i6.BitcoinAmount>.value(
              _FakeBitcoinAmount_38(this, Invocation.method(#getBalance, [])),
            ),
          )
          as _i12.Future<_i6.BitcoinAmount>);

  @override
  _i7.EvmChain getChainForEscrowService(_i8.EscrowService? service) =>
      (super.noSuchMethod(
            Invocation.method(#getChainForEscrowService, [service]),
            returnValue: _FakeEvmChain_39(
              this,
              Invocation.method(#getChainForEscrowService, [service]),
            ),
          )
          as _i7.EvmChain);

  @override
  _i4.ValueStream<_i6.BitcoinAmount> subscribeBalance() =>
      (super.noSuchMethod(
            Invocation.method(#subscribeBalance, []),
            returnValue: _FakeValueStream_2<_i6.BitcoinAmount>(
              this,
              Invocation.method(#subscribeBalance, []),
            ),
          )
          as _i4.ValueStream<_i6.BitcoinAmount>);

  @override
  _i12.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i7.EvmChain> getClientForChainId(int? chainId) =>
      (super.noSuchMethod(
            Invocation.method(#getClientForChainId, [chainId]),
            returnValue: _i12.Future<_i7.EvmChain>.value(
              _FakeEvmChain_39(
                this,
                Invocation.method(#getClientForChainId, [chainId]),
              ),
            ),
          )
          as _i12.Future<_i7.EvmChain>);
}

/// A class which mocks [Relays].
///
/// See the documentation for Mockito's code generation for more information.
class MockRelays extends _i1.Mock implements _i7.Relays {
  MockRelays() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.CustomLogger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeCustomLogger_6(this, Invocation.getter(#logger)),
          )
          as _i6.CustomLogger);

  @override
  _i2.Ndk get ndk =>
      (super.noSuchMethod(
            Invocation.getter(#ndk),
            returnValue: _FakeNdk_0(this, Invocation.getter(#ndk)),
          )
          as _i2.Ndk);

  @override
  _i3.RelayStorage get relayStorage =>
      (super.noSuchMethod(
            Invocation.getter(#relayStorage),
            returnValue: _FakeRelayStorage_40(
              this,
              Invocation.getter(#relayStorage),
            ),
          )
          as _i3.RelayStorage);

  @override
  _i12.Future<void> add(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#add, [url]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> remove(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [url]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> connect() =>
      (super.noSuchMethod(
            Invocation.method(#connect, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Stream<Map<String, _i13.RelayConnectivity<dynamic>>> connectivity() =>
      (super.noSuchMethod(
            Invocation.method(#connectivity, []),
            returnValue:
                _i12.Stream<
                  Map<String, _i13.RelayConnectivity<dynamic>>
                >.empty(),
          )
          as _i12.Stream<Map<String, _i13.RelayConnectivity<dynamic>>>);
}
