# Nostr-rs-relay configuration (production)

[info]
relay_url = "wss://relay.hostr.network"
name = "Hostr"
description = "Hostr production relay."

[network]
address = "0.0.0.0"
port = 80

[grpc]
event_admission_server = "http://relay-authz:50051"
restricts_write = true

[options]
reject_future_seconds = 1800

[authorization]
nip42_auth = true
nip42_dms = true

[limits]
limit_scrapers = false
