targets:
  $default:
    builders:
      swagger_dart_code_generator:
        options:
          include_if_null: false
          input_folder: lib/data/sources/boltz/swagger
          output_folder: lib/data/sources/boltz/swagger_generated

      mockito|mockBuilder:
        generate_for:
          - lib/mocks/**.dart
        options:
          # build_extensions takes a source pattern and if it matches it will transform the output
          # to your desired path. The default behaviour is to the .mocks.dart file to be in the same
          # directory as the source .dart file. As seen below this is customizable, but the generated
          # file must always end in `.mocks.dart`.
          #
          # If you specify custom build_extensions you MUST ensure that they cover all input files
          build_extensions:
            '^lib/mocks/{{}}.dart' : 'lib/mocks/{{}}.mocks.dart'

builders:
  mockBuilder:
    import: "package:mockito/src/builder.dart"
    builder_factories: ["buildMocks"]
    build_extensions: {".dart": [".mocks.dart"]}
    build_to: source
    auto_apply: dependents
    defaults:
      generate_for: ['test/**', 'lib/mocks/**']