env                        = "production"
project_id                 = "hostr-production-d3ba05b4"
domain_name                = "hostr.network"
google_maps_web_map_id     = "34b909422156ae99c6152cd1"
google_maps_android_map_id = ""
google_maps_ios_map_id     = ""
