env                        = "staging"
project_id                 = "hostr-staging-d4c52998"
domain_name                = "staging.hostr.network"
compose_machine_type       = "n2d-standard-2"
google_maps_web_map_id     = "ebc1f6bade270e33c10ed21b"
google_maps_android_map_id = ""
google_maps_ios_map_id     = ""
