FROM nginx:1.27-alpine
COPY landing-page/index.html /usr/share/nginx/html/index.html
COPY landing-page/assets/logo/ /usr/share/nginx/html/assets/logo/
COPY app/screenshots/iphone_17_pro_max/dark/ /usr/share/nginx/html/assets/screenshot/
COPY app/screenshots/iphone_17_pro_max/dark/ /usr/share/nginx/html/screenshot/
EXPOSE 80
