#!/usr/bin/env dart

/// Generates Dart env constant files from `.env.*` files.
///
/// Usage:
///   dart run scripts/generate-dart-env.dart <local|test|staging|prod>
///
/// Reads the relevant `.env` file(s), extracts known config variables, and
/// writes a typed Dart constants file into
/// `hostr_sdk/lib/config/generated/<env>_env.g.dart`.
///
/// The generated files are committed to the repo so that `dart test` and
/// `flutter run` work without any env-var sourcing.
library;

import 'dart:io';

// ──────────────────────────────────────────────────────────────────────
// Env → generated-file mapping
// ──────────────────────────────────────────────────────────────────────

/// Which `.env` files to read (relative to repo root) for each target.
/// Order matters — later files override earlier ones.
const envSources = {
  'local': ['.env', '.env.local'],
  'test': ['.env', '.env.test'],
  'staging': ['.env.staging'],
  'prod': ['.env.prod'],
};

/// Output filename within `hostr_sdk/lib/config/generated/`.
const outputFile = {
  'local': 'development_env.g.dart',
  'test': 'test_env.g.dart',
  'staging': 'staging_env.g.dart',
  'prod': 'production_env.g.dart',
};

// ──────────────────────────────────────────────────────────────────────
// Main
// ──────────────────────────────────────────────────────────────────────

void main(List<String> args) {
  if (args.isEmpty || !envSources.containsKey(args.first)) {
    stderr.writeln('Usage: generate-dart-env.dart <local|test|staging|prod>');
    exit(64);
  }

  final target = args.first;
  final repoRoot = _findRepoRoot();
  final vars = _loadEnvFiles(repoRoot, envSources[target]!);
  final code = _generateDart(target, vars);

  final outDir = Directory('${repoRoot.path}/hostr_sdk/lib/config/generated');
  if (!outDir.existsSync()) outDir.createSync(recursive: true);

  final outPath = '${outDir.path}/${outputFile[target]}';
  File(outPath).writeAsStringSync(code);
  stdout.writeln('Wrote $outPath');
}

// ──────────────────────────────────────────────────────────────────────
// Helpers
// ──────────────────────────────────────────────────────────────────────

Directory _findRepoRoot() {
  var dir = File(Platform.script.toFilePath()).parent;
  if (File('${Directory.current.path}/.env').existsSync()) {
    return Directory.current;
  }
  for (var i = 0; i < 5; i++) {
    if (File('${dir.path}/.env').existsSync()) return dir;
    dir = dir.parent;
  }
  stderr.writeln('Could not locate repo root (no .env found)');
  exit(1);
}

Map<String, String> _loadEnvFiles(Directory root, List<String> files) {
  final vars = <String, String>{};
  for (final relPath in files) {
    final f = File('${root.path}/$relPath');
    if (!f.existsSync()) {
      stderr.writeln('Warning: $relPath not found — skipping');
      continue;
    }
    for (final line in f.readAsLinesSync()) {
      final match = RegExp(r'^([A-Za-z0-9_]+)=(.*)$').firstMatch(line);
      if (match == null) continue;
      vars[match.group(1)!] = match.group(2)!;
    }
  }
  return vars;
}

String _generateDart(String target, Map<String, String> vars) {
  String v(String key) => vars[key] ?? '';
  String q(String key) => "'${_escape(v(key))}'";

  final buf = StringBuffer()
    ..writeln('// GENERATED by scripts/generate-dart-env.dart — DO NOT EDIT.')
    ..writeln('// Source: ${envSources[target]!.join(" + ")}')
    ..writeln(
      '// ignore_for_file: constant_identifier_names, avoid_escaping_inner_quotes',
    )
    ..writeln()
    ..writeln("import 'package:hostr_sdk/usecase/evm/config/evm_config.dart';")
    ..writeln();

  // ── Scalar app-level constants ──

  buf.writeln('const boltzApiUrl = ${q('BOLTZ_API_URL')};');
  buf.writeln('const relayUrl = ${q('RELAY_URL')};');
  buf.writeln('const blossomUrl = ${q('BLOSSOM_URL')};');
  buf.writeln('const tipsAddress = ${q('TIPS_ADDRESS')};');
  buf.writeln('const googleMapsApiKey = ${q('GOOGLE_MAPS_API_KEY')};');
  buf.writeln();

  // ── Bootstrap relays (comma-separated → List<String>) ──
  final relaysList = v(
    'BOOTSTRAP_RELAYS',
  ).split(',').map((e) => e.trim()).where((e) => e.isNotEmpty).toList();
  buf.writeln('const bootstrapRelays = <String>[');
  for (final r in relaysList) {
    buf.writeln("  '${_escape(r)}',");
  }
  buf.writeln('];');
  buf.writeln();

  // ── Bootstrap escrow pubkeys (comma-separated → List<String>) ──
  final pubkeys = v(
    'HOSTR_BOOTSTRAP_ESCROW_PUBKEY',
  ).split(',').map((e) => e.trim()).where((e) => e.isNotEmpty).toList();
  buf.writeln('const bootstrapEscrowPubkeys = <String>[');
  for (final pk in pubkeys) {
    buf.writeln("  '${_escape(pk)}',");
  }
  buf.writeln('];');
  buf.writeln();

  // ── Telemetry ──
  final telemetryEnabled = v('TELEMETRY_ENABLED').toLowerCase() == 'true';
  final telemetryEndpoint = v('TELEMETRY_ENDPOINT');
  final telemetryServiceName = v('TELEMETRY_SERVICE_NAME');
  buf.writeln('const telemetryEnabled = $telemetryEnabled;');
  buf.writeln("const telemetryEndpoint = '${_escape(telemetryEndpoint)}';");
  buf.writeln(
    "const telemetryServiceName = '${_escape(telemetryServiceName.isEmpty ? 'hostr-app' : telemetryServiceName)}';",
  );
  buf.writeln();

  // ── Per-chain EVM config (EVM_CHAINS + EVM_CHAIN_<ID>_*) ──
  final chainIds = v(
    'EVM_CHAINS',
  ).split(',').map((e) => e.trim()).where((e) => e.isNotEmpty).toList();

  buf.writeln('const evmConfig = EvmConfig(');
  buf.writeln('  boltz: BoltzConfig(apiUrl: boltzApiUrl),');
  buf.writeln('  chains: [');

  for (final chainId in chainIds) {
    final prefix = 'EVM_CHAIN_${chainId.toUpperCase().replaceAll('-', '_')}';
    final chainIdNum = int.tryParse(vars['${prefix}_CHAIN_ID'] ?? '') ?? 0;
    final rpcUrl = vars['${prefix}_RPC_URL'] ?? '';

    // AA config — per-chain
    final aaBundlerUrl = vars['${prefix}_AA_BUNDLER_URL'] ?? '';
    final aaEntryPoint = vars['${prefix}_AA_ENTRY_POINT_ADDRESS'] ?? '';
    final aaAccountFactory = vars['${prefix}_AA_ACCOUNT_FACTORY_ADDRESS'] ?? '';
    final aaPaymaster = vars['${prefix}_AA_PAYMASTER_ADDRESS'] ?? '';

    // Boltz native currency (e.g. 'RBTC') — per-chain
    final boltzCurrency = vars['${prefix}_BOLTZ_CURRENCY'] ?? '';

    // Token addresses — per-chain only
    final tbtcAddr = vars['${prefix}_TBTC_ADDRESS'] ?? '';
    final tbtcDec = int.tryParse(vars['${prefix}_TBTC_DECIMALS'] ?? '') ?? 18;
    final tbtcBalSlot = int.tryParse(
      vars['${prefix}_TBTC_BALANCE_STORAGE_SLOT'] ?? '',
    );
    final tbtcAlwSlot = int.tryParse(
      vars['${prefix}_TBTC_ALLOWANCE_STORAGE_SLOT'] ?? '',
    );
    final usdtAddr = vars['${prefix}_USDT_ADDRESS'] ?? '';
    final usdtDec = int.tryParse(vars['${prefix}_USDT_DECIMALS'] ?? '') ?? 6;
    final usdtBalSlot = int.tryParse(
      vars['${prefix}_USDT_BALANCE_STORAGE_SLOT'] ?? '',
    );
    final usdtAlwSlot = int.tryParse(
      vars['${prefix}_USDT_ALLOWANCE_STORAGE_SLOT'] ?? '',
    );

    buf.writeln('    EvmChainConfig(');
    buf.writeln("      id: '${_escape(chainId)}',");
    buf.writeln('      chainId: $chainIdNum,');
    buf.writeln("      rpcUrl: '${_escape(rpcUrl)}',");
    if (boltzCurrency.isNotEmpty) {
      buf.writeln("      boltzCurrency: '${_escape(boltzCurrency)}',");
    }
    final escrowAddr = vars['${prefix}_ESCROW_CONTRACT_ADDRESS'] ?? '';

    // AA — inline per-chain
    final hasAA =
        aaBundlerUrl.isNotEmpty ||
        aaEntryPoint.isNotEmpty ||
        aaAccountFactory.isNotEmpty ||
        aaPaymaster.isNotEmpty;
    if (hasAA) {
      buf.writeln('      accountAbstraction: AAConfig(');
      buf.writeln("        bundlerUrl: '${_escape(aaBundlerUrl)}',");
      buf.writeln("        entryPointAddress: '${_escape(aaEntryPoint)}',");
      buf.writeln(
        "        accountFactoryAddress: '${_escape(aaAccountFactory)}',",
      );
      buf.writeln("        paymasterAddress: '${_escape(aaPaymaster)}',");
      buf.writeln('      ),');
    }

    if (escrowAddr.isNotEmpty) {
      buf.writeln("      escrowContractAddress: '${_escape(escrowAddr)}',");
    }

    // Tokens map
    final hasTokens = tbtcAddr.isNotEmpty || usdtAddr.isNotEmpty;
    if (hasTokens) {
      buf.writeln('      tokens: {');
      if (tbtcAddr.isNotEmpty) {
        buf.writeln("        'tBTC': TokenConfig(");
        buf.writeln("          address: '${_escape(tbtcAddr)}',");
        buf.writeln('          decimals: $tbtcDec,');
        if (tbtcBalSlot != null) {
          buf.writeln('          balanceStorageSlot: $tbtcBalSlot,');
        }
        if (tbtcAlwSlot != null) {
          buf.writeln('          allowanceStorageSlot: $tbtcAlwSlot,');
        }
        buf.writeln('        ),');
      }
      if (usdtAddr.isNotEmpty) {
        buf.writeln("        'USDT': TokenConfig(");
        buf.writeln("          address: '${_escape(usdtAddr)}',");
        buf.writeln('          decimals: $usdtDec,');
        if (usdtBalSlot != null) {
          buf.writeln('          balanceStorageSlot: $usdtBalSlot,');
        }
        if (usdtAlwSlot != null) {
          buf.writeln('          allowanceStorageSlot: $usdtAlwSlot,');
        }
        buf.writeln('        ),');
      }
      buf.writeln('      },');
    }

    buf.writeln('    ),');
  }

  buf.writeln('  ],');
  buf.writeln(');');
  buf.writeln();

  return buf.toString();
}

String _escape(String s) => s.replaceAll(r'\', r'\\').replaceAll("'", r"\'");
