#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENVIRONMENT="${1:-local}"

case "$ENVIRONMENT" in
    local|test|staging|prod) ;;
    *)
        echo "Usage: $0 [local|test|staging|prod]"
        exit 64
        ;;
esac

restart_hostr() {
    (cd "$REPO_ROOT/dependencies/boltz-regtest" && ./stop.sh) || true
    (set -a; source "$REPO_ROOT/.env"; source "$REPO_ROOT/.env.$ENVIRONMENT"; set +a; cd "$REPO_ROOT" && docker compose down --volumes --remove-orphans) || true

    # Remove the old dev CA from the macOS system keychain before deleting
    # the cert files, so the new CA generated by tls-init can be trusted cleanly.
    if [[ "$OSTYPE" == darwin* ]] && [ -f "$REPO_ROOT/docker/tls/ca/ca.crt" ]; then
        CA_SHA1=$(openssl x509 -in "$REPO_ROOT/docker/tls/ca/ca.crt" -noout -fingerprint -sha1 2>/dev/null \
            | sed 's/.*=//' | tr -d ':')
        if [ -n "$CA_SHA1" ] && security find-certificate -a -Z /Library/Keychains/System.keychain 2>/dev/null \
           | grep -qi "$CA_SHA1"; then
            echo "→ Removing old Hostr dev CA from macOS system keychain..."
            sudo security delete-certificate -Z "$CA_SHA1" -t /Library/Keychains/System.keychain 2>/dev/null || true
        fi
    fi

    rm -rf \
        "$REPO_ROOT/docker/data/lightning_data" \
        "$REPO_ROOT/docker/data/bitcoin" \
        "$REPO_ROOT/docker/data/lnbits" \
        "$REPO_ROOT/docker/data/albyhub" \
        "$REPO_ROOT/docker/data/relay" \
        "$REPO_ROOT/docker/data/blossom" \
        "$REPO_ROOT/docker/data/escrow" \
        "$REPO_ROOT/docker/tls/ca/ca.crt" \
        "$REPO_ROOT/docker/tls/ca/ca.key" \
        "$REPO_ROOT/docker/tls/ca/ca.srl" \
        "$REPO_ROOT/docker/tls/ca/ca-bundle.crt" \
        "$REPO_ROOT/docker/certs"/*.crt \
        "$REPO_ROOT/docker/certs"/*.key \
        "$REPO_ROOT/escrow/contracts/ignition/deployments/chain-33" \
        "$REPO_ROOT/escrow/contracts/ignition/deployments/chain-31337" \
        "$REPO_ROOT/escrow/contracts/ignition/deployments"

    mkdir -p \
        "$REPO_ROOT/docker/data/lightning_data/1" \
        "$REPO_ROOT/docker/data/lightning_data/2" \
        "$REPO_ROOT/docker/data/bitcoin" \
        "$REPO_ROOT/docker/data/lnbits/1" \
        "$REPO_ROOT/docker/data/lnbits/2" \
        "$REPO_ROOT/docker/data/albyhub" \
        "$REPO_ROOT/docker/data/relay" \
        "$REPO_ROOT/docker/data/blossom" \
        "$REPO_ROOT/docker/data/escrow"

    # nostr-rs-relay runs as a non-root user in its container and needs write
    # access to the mounted sqlite path.
    chmod 0777 "$REPO_ROOT/docker/data/relay"

    (cd "$REPO_ROOT/dependencies/boltz-regtest" && git clean -fdx data/) || true

    # Re-pull boltz images for the selected platform so stale layers don't
    # shadow the architecture requested by compose.
    if [[ "${COMPOSE_FILE:-}" == *"dependencies/boltz-regtest/docker-compose.yml"* ]]; then
        (set -a; source "$REPO_ROOT/.env"; source "$REPO_ROOT/.env.$ENVIRONMENT"; \
            [ -f "$REPO_ROOT/dependencies/boltz-regtest/.env" ] && source "$REPO_ROOT/dependencies/boltz-regtest/.env"; \
            set +a; cd "$REPO_ROOT" && \
            docker compose pull --platform "${DOCKER_DEFAULT_PLATFORM:-linux/arm64}" boltz-backend boltz-backend-nginx boltz-client 2>/dev/null || true)
    fi

    "$SCRIPT_DIR/start.sh" "$ENVIRONMENT"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    restart_hostr "$@"
fi
